"""
Script d'import massif des effectifs CdM 2026
============================================
Usage :
  1. Renseigne ADMIN_TOKEN ci-dessous (récupère-le depuis localStorage.fb_token dans ton navigateur)
  2. Lance : python import_effectifs.py
  3. Pour n'importer qu'un groupe : python import_effectifs.py --groupe C
  4. Pour n'importer qu'une nation : python import_effectifs.py --nation "France"
"""

import requests
import json
import sys
import argparse
import time

# ── CONFIG ─────────────────────────────────────────────────────────────────────
API_BASE   = "http://localhost:8000"
ADMIN_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2U1OWNhMy05OWExLTRhODYtOTJiOS03ODVmYjE0NTliZmIiLCJlbWFpbCI6ImFkbWluQGZhbnRhc3kyNi5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3ODA5MDc0ODJ9.aswQqggqnCl5_ZtxOXgJkEoZFYx-pCakMWqGJC7_F0o"   # ← copie la valeur de localStorage.fb_token
# ──────────────────────────────────────────────────────────────────────────────
1111
HEADERS = {
    "Authorization": f"Bearer {ADMIN_TOKEN}",
    "Content-Type": "application/json",
}

def p(name, nat, pos, price=6.5):
    """Crée une entrée joueur."""
    return {"name": name, "nationality": nat, "position": pos,
            "team": nat, "price": int(round(price)), "age": None, "jersey_number": None}

def c(name, nat, price=6.5):
    """Crée une entrée entraîneur."""
    return {"name": name, "nationality": nat, "team": nat,
            "price": int(round(price)), "age": None}

def c(name, nat, price=6.5):
    """Crée une entrée entraîneur."""
    return {"name": name, "nationality": nat, "team": nat,
            "price": price, "age": None}

# ══════════════════════════════════════════════════════════════════════════════
#  EFFECTIFS PAR GROUPE
# ══════════════════════════════════════════════════════════════════════════════

EFFECTIFS = {

# ────────────────────────── GROUPE A ─────────────────────────────────────────
"Mexique": {
    "groupe": "A",
    "players": [
        p("Raul Rangel",        "Mexique", "GK", 5.0),
        p("Carlos Acevedo",     "Mexique", "GK", 5.5),
        p("Guillermo Ochoa",    "Mexique", "GK", 7.5),
        p("Israel Reyes",       "Mexique", "DEF", 5.5),
        p("Jesús Gallardo",     "Mexique", "DEF", 6.5),
        p("Jorge Sánchez",      "Mexique", "DEF", 7.0),
        p("César Montes",       "Mexique", "DEF", 7.0),
        p("Johan Vásquez",      "Mexique", "DEF", 7.0),
        p("Mateo Chávez",       "Mexique", "DEF", 6.0),
        p("Erik Lira",          "Mexique", "MID", 6.5),
        p("Luis Romo",          "Mexique", "MID", 6.5),
        p("Obed Vargas",        "Mexique", "MID", 8.0),
        p("Brian Gutiérrez",    "Mexique", "MID", 7.0),
        p("Orbelín Pineda",     "Mexique", "MID", 7.0),
        p("Edson Álvarez",      "Mexique", "MID", 9.5),
        p("Gilberto Mora",      "Mexique", "MID", 5.5),
        p("César Huerta",       "Mexique", "MID", 7.0),
        p("Álvaro Fidalgo",     "Mexique", "MID", 7.0),
        p("Luis Chávez",        "Mexique", "MID", 6.0),
        p("Roberto Alvarado",   "Mexique", "FWD", 7.0),
        p("Alexis Vega",        "Mexique", "FWD", 6.5),
        p("Julián Quiñones",    "Mexique", "FWD", 7.5),
        p("Santiago Gimenez",   "Mexique", "FWD", 10.5),
        p("Guillermo Martínez", "Mexique", "FWD", 5.5),
        p("Armando González",   "Mexique", "FWD", 5.5),
        p("Raúl Jiménez",       "Mexique", "FWD", 8.5),
    ],
    "coaches": [
        c("Javier Aguirre", "Mexique", 7.0),
    ],
},

"Afrique du Sud": {
    "groupe": "A",
    "players": [
        p("Ronwen Williams",       "Afrique du Sud", "GK", 8.0),
        p("Ricardo Goss",          "Afrique du Sud", "GK", 5.0),
        p("Sipho Chaine",          "Afrique du Sud", "GK", 6.0),
        p("Khuliso Mudau",         "Afrique du Sud", "DEF", 7.0),
        p("Olwethu Makhanya",      "Afrique du Sud", "DEF", 5.5),
        p("Bradley Cross",         "Afrique du Sud", "DEF", 5.5),
        p("Thabang Matuludi",      "Afrique du Sud", "DEF", 5.5),
        p("Nkosinathi Sibisi",     "Afrique du Sud", "DEF", 6.5),
        p("Aubrey Modiba",         "Afrique du Sud", "DEF", 6.0),
        p("Khulumani Ndamane",     "Afrique du Sud", "DEF", 5.5),
        p("Ime Okon",              "Afrique du Sud", "DEF", 6.0),
        p("Samukele Kabini",       "Afrique du Sud", "DEF", 5.5),
        p("Mbekezeli Mbokazi",     "Afrique du Sud", "DEF", 5.5),
        p("Teboho Mokoena",        "Afrique du Sud", "MID", 9.0),
        p("Jayden Adams",          "Afrique du Sud", "MID", 7.0),
        p("Thalente Mbatha",       "Afrique du Sud", "MID", 6.5),
        p("Kamogelo Sebelebele",   "Afrique du Sud", "MID", 6.0),
        p("Sphephelo Sithole",     "Afrique du Sud", "MID", 6.0),
        p("Oswin Appollis",        "Afrique du Sud", "FWD", 7.5),
        p("Tshepang Moremi",       "Afrique du Sud", "FWD", 5.5),
        p("Evidence Makgopa",      "Afrique du Sud", "FWD", 7.5),
        p("Lyle Foster",           "Afrique du Sud", "FWD", 8.0),
        p("Iqraam Rayners",        "Afrique du Sud", "FWD", 7.0),
        p("Relebohile Mofokeng",   "Afrique du Sud", "FWD", 8.0),
        p("Themba Zwane",          "Afrique du Sud", "FWD", 6.5),
        p("Thapelo Maseko",        "Afrique du Sud", "FWD", 6.0),
    ],
    "coaches": [
        c("Hugo Broos", "Afrique du Sud", 6.5),
    ],
},

"Corée du Sud": {
    "groupe": "A",
    "players": [
        p("Jo Hyeonwoo",       "Corée du Sud", "GK", 8.0),
        p("Kim Seunggyu",      "Corée du Sud", "GK", 6.0),
        p("Song Bumkeun",      "Corée du Sud", "GK", 5.5),
        p("Kim Minjae",        "Corée du Sud", "DEF", 11.0),
        p("Cho Wije",          "Corée du Sud", "DEF", 6.5),
        p("Lee Hanbeom",       "Corée du Sud", "DEF", 7.0),
        p("Kim Taehyeon",      "Corée du Sud", "DEF", 6.5),
        p("Park Jinseob",      "Corée du Sud", "DEF", 6.0),
        p("Lee Kihyuk",        "Corée du Sud", "DEF", 6.0),
        p("Lee Taeseok",       "Corée du Sud", "DEF", 6.0),
        p("Seol Youngwoo",     "Corée du Sud", "DEF", 7.0),
        p("Jens Castrop",      "Corée du Sud", "DEF", 7.0),
        p("Kim Moonhwan",      "Corée du Sud", "DEF", 6.0),
        p("Yang Hyunjun",      "Corée du Sud", "MID", 8.0),
        p("Paik Seungho",      "Corée du Sud", "MID", 7.0),
        p("Hwang Inbeom",      "Corée du Sud", "MID", 8.0),
        p("Kim Jinkyu",        "Corée du Sud", "MID", 6.5),
        p("Bae Junho",         "Corée du Sud", "MID", 6.5),
        p("Eom Jisung",        "Corée du Sud", "MID", 6.5),
        p("Hwang Heechan",     "Corée du Sud", "MID", 8.5),
        p("Lee Donggyeong",    "Corée du Sud", "MID", 7.0),
        p("Lee Jaesung",       "Corée du Sud", "MID", 7.0),
        p("Lee Kangin",        "Corée du Sud", "MID", 9.5),
        p("Oh Hyeongyu",       "Corée du Sud", "FWD", 8.0),
        p("Son Heungmin",      "Corée du Sud", "FWD", 11.5),
        p("Cho Guesung",       "Corée du Sud", "FWD", 7.5),
    ],
    "coaches": [
        c("Hong Myung-bo", "Corée du Sud", 6.5),
    ],
},

"Tchéquie": {
    "groupe": "A",
    "players": [
        p("Lukas Hornicek",    "Tchéquie", "GK", 6.0),
        p("Matej Kovar",       "Tchéquie", "GK", 8.0),
        p("Jindrich Stanek",   "Tchéquie", "GK", 7.5),
        p("Vladimir Coufal",   "Tchéquie", "DEF", 7.0),
        p("David Doudera",     "Tchéquie", "DEF", 6.5),
        p("Tomas Holes",       "Tchéquie", "DEF", 7.5),
        p("Robin Hranac",      "Tchéquie", "DEF", 7.5),
        p("Stepan Chaloupek",  "Tchéquie", "DEF", 6.0),
        p("David Jurasek",     "Tchéquie", "DEF", 7.0),
        p("Ladislav Krejci",   "Tchéquie", "DEF", 7.0),
        p("Jaroslav Zeleny",   "Tchéquie", "DEF", 6.0),
        p("David Zima",        "Tchéquie", "DEF", 6.5),
        p("Lukas Cerv",        "Tchéquie", "MID", 6.5),
        p("Vladimir Darida",   "Tchéquie", "MID", 6.0),
        p("Lukas Provod",      "Tchéquie", "MID", 7.5),
        p("Michal Sadilek",    "Tchéquie", "MID", 7.0),
        p("Hugo Sochurek",     "Tchéquie", "MID", 6.0),
        p("Alexandr Sojka",    "Tchéquie", "MID", 6.5),
        p("Tomas Soucek",      "Tchéquie", "MID", 9.5),
        p("Pavel Sulc",        "Tchéquie", "MID", 8.0),
        p("Denis Visinsky",    "Tchéquie", "MID", 6.5),
        p("Adam Hlozek",       "Tchéquie", "FWD", 8.5),
        p("Tomas Chory",       "Tchéquie", "FWD", 7.0),
        p("Mojmir Chytil",     "Tchéquie", "FWD", 7.0),
        p("Jan Kuchta",        "Tchéquie", "FWD", 6.5),
        p("Patrik Schick",     "Tchéquie", "FWD", 10.5),
    ],
    "coaches": [
        c("Miroslav Koubek", "Tchéquie", 6.0),
    ],
},
# ────────────────────────── GROUPE B ─────────────────────────────────────────

"Canada": {
    "groupe": "B",
    "players": [
        p("Dayne St. Clair",      "Canada", "GK", 8.0),
        p("Maxime Crépeau",       "Canada", "GK", 7.0),
        p("Owen Goodman",         "Canada", "GK", 6.0),
        p("Alistair Johnson",     "Canada", "DEF", 8.5),
        p("Derek Cornelius",      "Canada", "DEF", 7.5),
        p("Richie Laryea",        "Canada", "DEF", 7.0),
        p("Niko Sigur",           "Canada", "DEF", 6.0),
        p("Joel Waterman",        "Canada", "DEF", 6.5),
        p("Luc De Fougerolles",   "Canada", "DEF", 7.0),
        p("Moïse Bombito",        "Canada", "DEF", 7.5),
        p("Alphonso Davies",      "Canada", "DEF", 11.5),
        p("Alfie Jones",          "Canada", "DEF", 6.0),
        p("Stephen Eustáquio",    "Canada", "MID", 9.5),
        p("Ismaël Koné",          "Canada", "MID", 8.0),
        p("Tajon Buchanan",       "Canada", "MID", 8.5),
        p("Mathieu Choinière",    "Canada", "MID", 7.0),
        p("Ali Ahmed",            "Canada", "MID", 6.5),
        p("Nathan Saliba",        "Canada", "MID", 6.0),
        p("Liam Miller",          "Canada", "MID", 6.0),
        p("Marcelo Flores",       "Canada", "MID", 7.5),
        p("Jacob Shaffelburg",    "Canada", "MID", 6.5),
        p("Jonathan Osario",      "Canada", "MID", 6.5),
        p("Jonathan David",       "Canada", "FWD", 11.0),
        p("Cyle Larin",           "Canada", "FWD", 7.5),
        p("Tani Oluwaseyi",       "Canada", "FWD", 7.0),
        p("Promise David",        "Canada", "FWD", 6.5),
    ],
    "coaches": [
        c("Jesse Marsch", "Canada", 7.0),
    ],
},

"Bosnie-Herzégovine": {
    "groupe": "B",
    "players": [
        p("Nikola Vasilj",         "Bosnie-Herzégovine", "GK", 7.5),
        p("Martin Zlomislić",      "Bosnie-Herzégovine", "GK", 5.0),
        p("Osman Hadžikić",        "Bosnie-Herzégovine", "GK", 5.5),
        p("Sead Kolašinac",        "Bosnie-Herzégovine", "DEF", 9.0),
        p("Amar Dedić",            "Bosnie-Herzégovine", "DEF", 8.5),
        p("Nihad Mujakić",         "Bosnie-Herzégovine", "DEF", 6.0),
        p("Nikola Katić",          "Bosnie-Herzégovine", "DEF", 7.0),
        p("Tarik Muharemović",     "Bosnie-Herzégovine", "DEF", 7.5),
        p("Stjepan Radeljić",      "Bosnie-Herzégovine", "DEF", 6.5),
        p("Dennis Hadžikadunić",   "Bosnie-Herzégovine", "DEF", 6.5),
        p("Nidal Čelik",           "Bosnie-Herzégovine", "DEF", 6.5),
        p("Amir Hadžiahmetović",   "Bosnie-Herzégovine", "MID", 7.5),
        p("Ivan Šunjić",           "Bosnie-Herzégovine", "MID", 7.0),
        p("Ivan Bašić",            "Bosnie-Herzégovine", "MID", 6.0),
        p("Dženis Burnić",         "Bosnie-Herzégovine", "MID", 6.5),
        p("Ermin Mahmić",          "Bosnie-Herzégovine", "MID", 6.0),
        p("Benjamin Tahirović",    "Bosnie-Herzégovine", "MID", 7.5),
        p("Amar Memić",            "Bosnie-Herzégovine", "MID", 6.5),
        p("Armin Gigović",         "Bosnie-Herzégovine", "MID", 7.0),
        p("Kerim Alajbegović",     "Bosnie-Herzégovine", "FWD", 7.0),
        p("Esmir Bajraktarević",   "Bosnie-Herzégovine", "FWD", 7.5),
        p("Ermedin Demirović",     "Bosnie-Herzégovine", "FWD", 9.0),
        p("Jovo Lukić",            "Bosnie-Herzégovine", "FWD", 6.0),
        p("Samed Baždar",          "Bosnie-Herzégovine", "FWD", 6.5),
        p("Haris Tabaković",       "Bosnie-Herzégovine", "FWD", 7.0),
        p("Edin Džeko",            "Bosnie-Herzégovine", "FWD", 9.5),
    ],
    "coaches": [
        c("Sergej Barbarez", "Bosnie-Herzégovine", 6.0),
    ],
},

"Qatar": {
    "groupe": "B",
    "players": [
        p("Salah Zakaria",         "Qatar", "GK", 5.5),
        p("Mahmoud Abunada",       "Qatar", "GK", 5.0),
        p("Meshaal Barsham",       "Qatar", "GK", 7.0),
        p("Hashmi Hussein",        "Qatar", "DEF", 6.0),
        p("Ayoub Alawi",           "Qatar", "DEF", 6.5),
        p("Boualem Khoukhi",       "Qatar", "DEF", 7.5),
        p("Pedro Miguel",          "Qatar", "DEF", 7.5),
        p("Issa Laaye",            "Qatar", "DEF", 6.0),
        p("Lucas Mendes",          "Qatar", "DEF", 6.5),
        p("Sultan Al-Brake",       "Qatar", "DEF", 7.0),
        p("Homam Al-Amin",         "Qatar", "DEF", 6.0),
        p("Mohammed Al-Manai",     "Qatar", "MID", 6.0),
        p("Jassem Jaber",          "Qatar", "MID", 6.5),
        p("Karim Boudiaf",         "Qatar", "MID", 7.5),
        p("Ahmed Fathi",           "Qatar", "MID", 6.5),
        p("Abdulaziz Hatem",       "Qatar", "MID", 7.0),
        p("Assim Madibo",          "Qatar", "MID", 7.0),
        p("Tahseen Mohammed",      "Qatar", "FWD", 6.0),
        p("Edmilson Junior",       "Qatar", "FWD", 7.5),
        p("Almoez Ali",            "Qatar", "FWD", 9.0),
        p("Akram Afif",            "Qatar", "FWD", 10.0),
        p("Mohammed Muntari",      "Qatar", "FWD", 7.5),
        p("Youssef Abdulrazzaq",   "Qatar", "FWD", 6.0),
        p("Ahmed Alaa",            "Qatar", "FWD", 6.0),
        p("Hassan Al-Haydos",      "Qatar", "FWD", 7.0),
        p("Ahmed Al-Janahi",       "Qatar", "FWD", 6.5),
    ],
    "coaches": [
        c("Julen Lopetegui", "Qatar", 8.0),
    ],
},

"Suisse": {
    "groupe": "B",
    "players": [
        p("Marvin Keller",     "Suisse", "GK", 5.0),
        p("Gregor Kobel",      "Suisse", "GK", 7.5),
        p("Yvon Mvogo",        "Suisse", "GK", 5.5),
        p("Manuel Akanji",     "Suisse", "DEF", 9.0),
        p("Aurèle Amenda",     "Suisse", "DEF", 6.0),
        p("Eray Cömert",       "Suisse", "DEF", 6.0),
        p("Nico Elvedi",       "Suisse", "DEF", 7.0),
        p("Luca Jaquez",       "Suisse", "DEF", 5.5),
        p("Miro Muheim",       "Suisse", "DEF", 5.5),
        p("Ricardo Rodríguez", "Suisse", "DEF", 7.0),
        p("Silvan Widmer",     "Suisse", "DEF", 6.5),
        p("Michel Aebischer",  "Suisse", "MID", 6.0),
        p("Remo Freuler",      "Suisse", "MID", 8.0),
        p("Ardon Jashari",     "Suisse", "MID", 8.5),
        p("Fabian Rieder",     "Suisse", "MID", 7.0),
        p("Djibril Sow",       "Suisse", "MID", 7.5),
        p("Granit Xhaka",      "Suisse", "MID", 9.0),
        p("Denis Zakaria",     "Suisse", "MID", 7.0),
        p("Zeki Amdouni",      "Suisse", "FWD", 7.0),
        p("Breel Embolo",      "Suisse", "FWD", 8.0),
        p("Dan Ndoye",         "Suisse", "FWD", 8.5),
        p("Noah Okafor",       "Suisse", "FWD", 8.0),
        p("Rubén Vargas",      "Suisse", "FWD", 7.5),
        p("Christian Fassnacht","Suisse","FWD", 6.5),
        p("Cedric Itten",      "Suisse", "FWD", 6.0),
        p("Johan Manzambi",    "Suisse", "FWD", 5.5),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE C ─────────────────────────────────────────
"Brésil": {
    "groupe": "C",
    "players": [
        p("Alisson",           "Brésil", "GK", 11.0),
        p("Ederson",           "Brésil", "GK", 9.0),
        p("Weverton",          "Brésil", "GK", 5.5),
        p("Wesley",            "Brésil", "DEF", 7.0),
        p("Douglas Santos",    "Brésil", "DEF", 6.0),
        p("Alex Sandro",       "Brésil", "DEF", 6.0),
        p("Gabriel Magalhães", "Brésil", "DEF", 9.0),
        p("Marquinhos",        "Brésil", "DEF", 10.5),
        p("Danilo",            "Brésil", "DEF", 7.0),
        p("Bremer",            "Brésil", "DEF", 8.5),
        p("Ibañez",            "Brésil", "DEF", 6.5),
        p("Léo Pereira",       "Brésil", "DEF", 7.0),
        p("Bruno Guimarães",   "Brésil", "MID", 10.0),
        p("Casemiro",          "Brésil", "MID", 9.0),
        p("Danilo Santos",     "Brésil", "MID", 6.5),
        p("Fabinho",           "Brésil", "MID", 8.0),
        p("Lucas Paquetá",     "Brésil", "MID", 9.5),
        p("Raphinha",          "Brésil", "FWD", 10.0),
        p("Neymar",            "Brésil", "FWD", 10.0),
        p("Vinícius Júnior",   "Brésil", "FWD", 12.0),
        p("Luiz Henrique",     "Brésil", "FWD", 7.0),
        p("Matheus Cunha",     "Brésil", "FWD", 8.5),
        p("Gabriel Martinelli","Brésil", "FWD", 9.0),
        p("Igor Thiago",       "Brésil", "FWD", 7.0),
        p("Endrick",           "Brésil", "FWD", 8.5),
        p("Rayan",             "Brésil", "FWD", 7.0),
    ],
    "coaches": [],
},

"Maroc": {
    "groupe": "C",
    "players": [
        p("Yassine Bounou",       "Maroc", "GK", 10.0),
        p("Munir El Kajoui",      "Maroc", "GK", 5.5),
        p("Ahmed Reda Tagnaouti", "Maroc", "GK", 5.0),
        p("Noussair Mazraoui",    "Maroc", "DEF", 9.0),
        p("Anass Salah-Eddine",   "Maroc", "DEF", 6.5),
        p("Youssef Belammari",    "Maroc", "DEF", 5.5),
        p("Nayef Aguerd",         "Maroc", "DEF", 8.5),
        p("Chadi Riad",           "Maroc", "DEF", 7.0),
        p("Issa Diop",            "Maroc", "DEF", 7.0),
        p("Redouane Halhal",      "Maroc", "DEF", 5.5),
        p("Achraf Hakimi",        "Maroc", "DEF", 11.0),
        p("Zakaria El Ouahdi",    "Maroc", "DEF", 6.5),
        p("Samir El Mourabet",    "Maroc", "MID", 6.0),
        p("Ayyoub Bouaddi",       "Maroc", "MID", 8.0),
        p("Neil El Aynaoui",      "Maroc", "MID", 7.5),
        p("Sofyan Amrabat",       "Maroc", "MID", 9.0),
        p("Azzedine Ounahi",      "Maroc", "MID", 8.0),
        p("Bilal El Khannouss",   "Maroc", "MID", 8.5),
        p("Ismael Saibari",       "Maroc", "MID", 7.5),
        p("Abdessamad Ezzalzouli","Maroc", "FWD", 8.0),
        p("Chemsdine Talbi",      "Maroc", "FWD", 7.0),
        p("Soufiane Rahimi",      "Maroc", "FWD", 7.5),
        p("Ayoub El Kaabi",       "Maroc", "FWD", 8.5),
        p("Brahim Diaz",          "Maroc", "FWD", 10.0),
        p("Yassine Gessime",      "Maroc", "FWD", 6.0),
        p("Ayoube Amaimouni",     "Maroc", "FWD", 6.0),
    ],
    "coaches": [],
},

"Haïti": {
    "groupe": "C",
    "players": [
        p("Johnny Placide",         "Haïti", "GK", 5.0),
        p("Alexandre Pierre",       "Haïti", "GK", 4.5),
        p("Josué Duverger",         "Haïti", "GK", 4.0),
        p("Carlens Arcus",          "Haïti", "DEF", 5.5),
        p("Wilguens Paugain",       "Haïti", "DEF", 5.0),
        p("Duke Lacroix",           "Haïti", "DEF", 4.5),
        p("Martin Experience",      "Haïti", "DEF", 5.0),
        p("Jean-Kevin Duverne",     "Haïti", "DEF", 6.5),
        p("Ricardo Adé",            "Haïti", "DEF", 5.5),
        p("Hannes Delcroix",        "Haïti", "DEF", 6.0),
        p("Keeto Thermoncy",        "Haïti", "DEF", 4.0),
        p("Leverton Pierre",        "Haïti", "MID", 5.0),
        p("Carl-Fred Sainthe",      "Haïti", "MID", 4.5),
        p("Jean-Jacques Danley",    "Haïti", "MID", 5.5),
        p("Jean-Ricner Bellegarde", "Haïti", "MID", 8.0),
        p("Pierre Woodenski",       "Haïti", "MID", 4.5),
        p("Dominique Simon",        "Haïti", "MID", 4.5),
        p("Louicius Deedson",       "Haïti", "FWD", 5.5),
        p("Ruben Providence",       "Haïti", "FWD", 5.5),
        p("Josué Casimir",          "Haïti", "FWD", 6.0),
        p("Derrick Etienne",        "Haïti", "FWD", 6.5),
        p("Wilson Isidor",          "Haïti", "FWD", 7.0),
        p("Duckens Nazon",          "Haïti", "FWD", 5.5),
        p("Frantzdy Pierrot",       "Haïti", "FWD", 6.0),
        p("Yassin Fortune",         "Haïti", "FWD", 5.0),
        p("Lenny Joseph",           "Haïti", "FWD", 5.5),
    ],
    "coaches": [],
},

"Écosse": {
    "groupe": "C",
    "players": [
        p("Craig Gordon",      "Écosse", "GK", 6.0),
        p("Angus Gunn",        "Écosse", "GK", 6.5),
        p("Liam Kelly",        "Écosse", "GK", 5.5),
        p("Grant Hanley",      "Écosse", "DEF", 6.0),
        p("Jack Hendry",       "Écosse", "DEF", 6.5),
        p("Aaron Hickey",      "Écosse", "DEF", 7.5),
        p("Dom Hyam",          "Écosse", "DEF", 5.5),
        p("Scott McKenna",     "Écosse", "DEF", 6.5),
        p("Nathan Patterson",  "Écosse", "DEF", 7.0),
        p("Anthony Ralston",   "Écosse", "DEF", 6.0),
        p("Andy Robertson",    "Écosse", "DEF", 10.0),
        p("John Souttar",      "Écosse", "DEF", 6.0),
        p("Kieran Tierney",    "Écosse", "DEF", 8.5),
        p("Ryan Christie",     "Écosse", "MID", 6.5),
        p("Findlay Curtis",    "Écosse", "MID", 5.0),
        p("Lewis Ferguson",    "Écosse", "MID", 7.5),
        p("Ben Gannon-Doak",   "Écosse", "MID", 6.0),
        p("Billy Gilmour",     "Écosse", "MID", 8.0),
        p("John McGinn",       "Écosse", "MID", 9.0),
        p("Kenny McLean",      "Écosse", "MID", 6.0),
        p("Scott McTominay",   "Écosse", "MID", 9.5),
        p("Ché Adams",         "Écosse", "FWD", 7.0),
        p("Lyndon Dykes",      "Écosse", "FWD", 6.5),
        p("George Hirst",      "Écosse", "FWD", 6.0),
        p("Lawrence Shankland","Écosse", "FWD", 7.5),
        p("Ross Stewart",      "Écosse", "FWD", 6.5),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE D ─────────────────────────────────────────
"États-Unis": {
    "groupe": "D",
    "players": [
        p("Chris Brady",        "États-Unis", "GK", 6.0),
        p("Matt Freese",        "États-Unis", "GK", 5.5),
        p("Matt Turner",        "États-Unis", "GK", 7.0),
        p("Max Arfsten",        "États-Unis", "DEF", 5.5),
        p("Sergiño Dest",       "États-Unis", "DEF", 8.0),
        p("Alex Freeman",       "États-Unis", "DEF", 6.5),
        p("Mark McKenzie",      "États-Unis", "DEF", 6.5),
        p("Tim Ream",           "États-Unis", "DEF", 6.0),
        p("Chris Richards",     "États-Unis", "DEF", 7.5),
        p("Antonee Robinson",   "États-Unis", "DEF", 8.5),
        p("Miles Robinson",     "États-Unis", "DEF", 7.0),
        p("Joe Scally",         "États-Unis", "DEF", 7.0),
        p("Auston Trusty",      "États-Unis", "DEF", 6.0),
        p("Tyler Adams",        "États-Unis", "MID", 8.5),
        p("Sebastian Berhalter","États-Unis", "MID", 5.5),
        p("Weston McKennie",    "États-Unis", "MID", 8.5),
        p("Gio Reyna",          "États-Unis", "MID", 8.5),
        p("Cristian Roldan",    "États-Unis", "MID", 6.5),
        p("Malik Tillman",      "États-Unis", "MID", 8.0),
        p("Brenden Aaronson",   "États-Unis", "FWD", 7.5),
        p("Folarin Balogun",    "États-Unis", "FWD", 8.0),
        p("Ricardo Pepi",       "États-Unis", "FWD", 8.0),
        p("Christian Pulisic",  "États-Unis", "FWD", 11.0),
        p("Tim Weah",           "États-Unis", "FWD", 7.5),
        p("Haji Wright",        "États-Unis", "FWD", 6.5),
        p("Alejandro Zendejas", "États-Unis", "FWD", 6.5),
    ],
    "coaches": [],
},

"Paraguay": {
    "groupe": "D",
    "players": [
        p("Gatito Fernández",   "Paraguay", "GK", 6.5),
        p("Orlando Gill",       "Paraguay", "GK", 5.0),
        p("Gastón Olveira",     "Paraguay", "GK", 5.0),
        p("Gustavo Gómez",      "Paraguay", "DEF", 8.5),
        p("Júnior Alonso",      "Paraguay", "DEF", 7.5),
        p("Fabián Balbuena",    "Paraguay", "DEF", 7.0),
        p("Omar Alderete",      "Paraguay", "DEF", 7.0),
        p("Juan José Cáceres",  "Paraguay", "DEF", 6.0),
        p("Gustavo Velázquez",  "Paraguay", "DEF", 5.5),
        p("José Canale",        "Paraguay", "DEF", 5.5),
        p("Alexandro Maidana",  "Paraguay", "DEF", 5.5),
        p("Miguel Almirón",     "Paraguay", "MID", 9.5),
        p("Kaku",               "Paraguay", "MID", 7.0),
        p("Andrés Cubas",       "Paraguay", "MID", 7.0),
        p("Ramón Sosa",         "Paraguay", "MID", 7.5),
        p("Diego Gómez",        "Paraguay", "MID", 8.0),
        p("Damián Bobadilla",   "Paraguay", "MID", 7.0),
        p("Braian Ojeda",       "Paraguay", "MID", 6.5),
        p("Matías Galarza",     "Paraguay", "MID", 6.5),
        p("Maurício",           "Paraguay", "MID", 7.0),
        p("Antonio Sanabria",   "Paraguay", "FWD", 7.5),
        p("Julio Enciso",       "Paraguay", "FWD", 8.5),
        p("Gabriel Ávalos",     "Paraguay", "FWD", 6.0),
        p("Álex Arce",          "Paraguay", "FWD", 6.0),
        p("Isidro Pitta",       "Paraguay", "FWD", 6.5),
        p("Gustavo Caballero",  "Paraguay", "FWD", 5.5),
    ],
    "coaches": [],
},

"Australie": {
    "groupe": "D",
    "players": [
        p("Mathew Ryan",         "Australie", "GK", 8.0),
        p("Paul Izzo",           "Australie", "GK", 5.5),
        p("Patrick Beach",       "Australie", "GK", 4.5),
        p("Aziz Behich",         "Australie", "DEF", 5.5),
        p("Jordan Bos",          "Australie", "DEF", 6.5),
        p("Cameron Burgess",     "Australie", "DEF", 6.0),
        p("Alessandro Circati",  "Australie", "DEF", 6.5),
        p("Milos Degenek",       "Australie", "DEF", 6.0),
        p("Jason Geria",         "Australie", "DEF", 5.5),
        p("Lucas Herrington",    "Australie", "DEF", 5.0),
        p("Jacob Italiano",      "Australie", "DEF", 5.0),
        p("Harry Souttar",       "Australie", "DEF", 7.5),
        p("Kai Trewin",          "Australie", "DEF", 5.0),
        p("Cameron Devlin",      "Australie", "MID", 6.5),
        p("Ajdin Hrustic",       "Australie", "MID", 7.0),
        p("Jackson Irvine",      "Australie", "MID", 7.5),
        p("Connor Metcalfe",     "Australie", "MID", 6.0),
        p("Paul Okon-Engstler",  "Australie", "MID", 4.5),
        p("Aiden O'Neill",       "Australie", "MID", 6.0),
        p("Nestory Irankunda",   "Australie", "FWD", 7.0),
        p("Mathew Leckie",       "Australie", "FWD", 7.5),
        p("Awer Mabil",          "Australie", "FWD", 7.0),
        p("Mohamed Toure",       "Australie", "FWD", 6.5),
        p("Nishan Velupillay",   "Australie", "FWD", 5.5),
        p("Christian Volpato",   "Australie", "FWD", 6.5),
        p("Tete Yengi",          "Australie", "FWD", 5.5),
    ],
    "coaches": [],
},

"Turquie": {
    "groupe": "D",
    "players": [
        p("Altay Bayındır",       "Turquie", "GK", 8.0),
        p("Mert Günok",           "Turquie", "GK", 7.0),
        p("Uğurcan Çakır",        "Turquie", "GK", 7.5),
        p("Abdülkerim Bardakcı",  "Turquie", "DEF", 8.0),
        p("Çağlar Söyüncü",       "Turquie", "DEF", 8.5),
        p("Eren Elmalı",          "Turquie", "DEF", 6.5),
        p("Ferdi Kadıoğlu",       "Turquie", "DEF", 9.0),
        p("Merih Demiral",        "Turquie", "DEF", 8.5),
        p("Mert Müldür",          "Turquie", "DEF", 7.0),
        p("Ozan Kabak",           "Turquie", "DEF", 7.5),
        p("Samet Akaydın",        "Turquie", "DEF", 6.0),
        p("Zeki Çelik",           "Turquie", "DEF", 7.5),
        p("Hakan Çalhanoğlu",     "Turquie", "MID", 11.0),
        p("İsmail Yüksek",        "Turquie", "MID", 7.0),
        p("Kaan Ayhan",           "Turquie", "MID", 7.0),
        p("Orkun Kökçü",          "Turquie", "MID", 8.0),
        p("Salih Özcan",          "Turquie", "MID", 7.5),
        p("Arda Güler",           "Turquie", "FWD", 10.0),
        p("Barış Alper Yılmaz",   "Turquie", "FWD", 8.0),
        p("Can Uzun",             "Turquie", "FWD", 7.5),
        p("Deniz Gül",            "Turquie", "FWD", 6.5),
        p("İrfan Can Kahveci",    "Turquie", "FWD", 7.0),
        p("Kenan Yıldız",         "Turquie", "FWD", 9.5),
        p("Kerem Aktürkoğlu",     "Turquie", "FWD", 8.5),
        p("Oğuz Aydın",           "Turquie", "FWD", 6.5),
        p("Yunus Akgün",          "Turquie", "FWD", 7.0),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE E ─────────────────────────────────────────
"Allemagne": {
    "groupe": "E",
    "players": [
        p("Oliver Baumann",    "Allemagne", "GK", 6.5),
        p("Manuel Neuer",      "Allemagne", "GK", 9.0),
        p("Alexander Nubel",   "Allemagne", "GK", 7.0),
        p("Waldemar Anton",    "Allemagne", "DEF", 7.5),
        p("Nathaniel Brown",   "Allemagne", "DEF", 6.5),
        p("Joshua Kimmich",    "Allemagne", "DEF", 10.5),
        p("David Raum",        "Allemagne", "DEF", 7.5),
        p("Antonio Rudiger",   "Allemagne", "DEF", 10.0),
        p("Nico Schlotterbeck","Allemagne", "DEF", 8.5),
        p("Jonathan Tah",      "Allemagne", "DEF", 8.0),
        p("Malick Thiaw",      "Allemagne", "DEF", 8.0),
        p("Nadiem Amiri",      "Allemagne", "MID", 6.5),
        p("Leon Goretzka",     "Allemagne", "MID", 8.5),
        p("Pascal Gross",      "Allemagne", "MID", 7.0),
        p("Jamie Leweling",    "Allemagne", "MID", 7.0),
        p("Lennart Karl",      "Allemagne", "MID", 6.0),
        p("Jamal Musiala",     "Allemagne", "MID", 11.0),
        p("Felix Nmecha",      "Allemagne", "MID", 7.5),
        p("Alexander Pavlovic","Allemagne", "MID", 7.5),
        p("Angelo Stiller",    "Allemagne", "MID", 7.5),
        p("Florian Wirtz",     "Allemagne", "FWD", 11.5),
        p("Maximilian Beier",  "Allemagne", "FWD", 7.5),
        p("Kai Havertz",       "Allemagne", "FWD", 10.0),
        p("Leroy Sane",        "Allemagne", "FWD", 9.5),
        p("Denis Undav",       "Allemagne", "FWD", 7.5),
        p("Nick Woltemade",    "Allemagne", "FWD", 6.5),
    ],
    "coaches": [],
},

"Curaçao": {
    "groupe": "E",
    "players": [
        p("Tyrick Bodak",        "Curaçao", "GK", 4.5),
        p("Trevor Doornbusch",   "Curaçao", "GK", 4.5),
        p("Eloy Room",           "Curaçao", "GK", 6.0),
        p("Riechedly Bazoer",    "Curaçao", "DEF", 6.5),
        p("Joshua Brenet",       "Curaçao", "DEF", 5.5),
        p("Roshon Van Eijma",    "Curaçao", "DEF", 5.0),
        p("Sherel Floranus",     "Curaçao", "DEF", 5.0),
        p("Deveron Fonville",    "Curaçao", "DEF", 5.5),
        p("Juriën Gaari",        "Curaçao", "DEF", 5.5),
        p("Armando Obispo",      "Curaçao", "DEF", 7.5),
        p("Shurandy Sambo",      "Curaçao", "DEF", 5.5),
        p("Juninho Bacuna",      "Curaçao", "MID", 6.5),
        p("Leandro Bacuna",      "Curaçao", "MID", 6.0),
        p("Livano Comenencia",   "Curaçao", "MID", 6.0),
        p("Kevin Felida",        "Curaçao", "MID", 5.0),
        p("Ar'Jany Martha",      "Curaçao", "MID", 5.5),
        p("Tyrese Noslin",       "Curaçao", "MID", 5.5),
        p("Godfried Roemeratoe", "Curaçao", "MID", 5.0),
        p("Jeremy Antonisse",    "Curaçao", "FWD", 5.0),
        p("Tahith Chong",        "Curaçao", "FWD", 7.0),
        p("Kenji Gorré",         "Curaçao", "FWD", 5.5),
        p("Sontje Hansen",       "Curaçao", "FWD", 6.0),
        p("Gervane Kastaneer",   "Curaçao", "FWD", 5.5),
        p("Brandley Kuwas",      "Curaçao", "FWD", 5.5),
        p("Jürgen Locadia",      "Curaçao", "FWD", 6.0),
        p("Jearl Margaritha",    "Curaçao", "FWD", 5.5),
    ],
    "coaches": [],
},

"Côte d'Ivoire": {
    "groupe": "E",
    "players": [
        p("Yahia Fofana",       "Côte d'Ivoire", "GK", 6.0),
        p("Mohamed Koné",       "Côte d'Ivoire", "GK", 5.0),
        p("Alban Lafont",       "Côte d'Ivoire", "GK", 7.0),
        p("Emmanuel Agbadou",   "Côte d'Ivoire", "DEF", 7.5),
        p("Clément Akpa",       "Côte d'Ivoire", "DEF", 5.5),
        p("Ousmane Diomandé",   "Côte d'Ivoire", "DEF", 9.0),
        p("Guéla Doué",         "Côte d'Ivoire", "DEF", 7.0),
        p("Ghislain Konan",     "Côte d'Ivoire", "DEF", 6.0),
        p("Odilon Kossounou",   "Côte d'Ivoire", "DEF", 8.5),
        p("Evan Ndicka",        "Côte d'Ivoire", "DEF", 8.5),
        p("Wilfried Singo",     "Côte d'Ivoire", "DEF", 7.5),
        p("Seko Fofana",        "Côte d'Ivoire", "MID", 8.5),
        p("Parfait Guiagon",    "Côte d'Ivoire", "MID", 5.5),
        p("Christ Inao Oulaï",  "Côte d'Ivoire", "MID", 5.5),
        p("Franck Kessié",      "Côte d'Ivoire", "MID", 9.0),
        p("Ibrahim Sangaré",    "Côte d'Ivoire", "MID", 8.5),
        p("Jean-Mickaël Seri",  "Côte d'Ivoire", "MID", 7.0),
        p("Simon Adingra",      "Côte d'Ivoire", "FWD", 8.5),
        p("Ange-Yoan Bonny",    "Côte d'Ivoire", "FWD", 7.5),
        p("Amad Diallo",        "Côte d'Ivoire", "FWD", 9.5),
        p("Oumar Diakité",      "Côte d'Ivoire", "FWD", 6.0),
        p("Yan Diomandé",       "Côte d'Ivoire", "FWD", 7.5),
        p("Evann Guessand",     "Côte d'Ivoire", "FWD", 7.0),
        p("Nicolas Pépé",       "Côte d'Ivoire", "FWD", 7.5),
        p("Bazoumana Touré",    "Côte d'Ivoire", "FWD", 6.0),
        p("Elye Wahi",          "Côte d'Ivoire", "FWD", 8.0),
    ],
    "coaches": [],
},

"Équateur": {
    "groupe": "E",
    "players": [
        p("Hernán Galíndez",    "Équateur", "GK", 6.5),
        p("Moisés Ramírez",     "Équateur", "GK", 5.5),
        p("Gonzalo Valle",      "Équateur", "GK", 5.0),
        p("Willian Pacho",      "Équateur", "DEF", 9.5),
        p("Piero Hincapié",     "Équateur", "DEF", 9.0),
        p("Joel Ordóñez",       "Équateur", "DEF", 7.5),
        p("Félix Torres",       "Équateur", "DEF", 7.5),
        p("Pervis Estupiñán",   "Équateur", "DEF", 9.0),
        p("Ángelo Preciado",    "Équateur", "DEF", 7.0),
        p("Jackson Porozo",     "Équateur", "DEF", 6.5),
        p("Moisés Caicedo",     "Équateur", "MID", 11.0),
        p("Jordy Alcívar",      "Équateur", "MID", 6.5),
        p("Denil Castillo",     "Équateur", "MID", 6.5),
        p("Alan Franco",        "Équateur", "MID", 7.0),
        p("Pedro Vite",         "Équateur", "MID", 6.0),
        p("Kendry Páez",        "Équateur", "MID", 8.5),
        p("Yaimar Medina",      "Équateur", "MID", 6.5),
        p("Kevin Rodríguez",    "Équateur", "FWD", 7.0),
        p("Anthony Valencia",   "Équateur", "FWD", 6.5),
        p("Enner Valencia",     "Équateur", "FWD", 8.0),
        p("Jordy Caicedo",      "Équateur", "FWD", 6.5),
        p("Jeremy Arévalo",     "Équateur", "FWD", 6.5),
        p("Gonzalo Plata",      "Équateur", "FWD", 7.5),
        p("Alan Minda",         "Équateur", "FWD", 6.0),
        p("John Yeboah",        "Équateur", "FWD", 6.0),
        p("Nilson Angulo",      "Équateur", "FWD", 6.5),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE F ─────────────────────────────────────────
"Pays-Bas": {
    "groupe": "F",
    "players": [
        p("Mark Flekken",        "Pays-Bas", "GK", 7.0),
        p("Robin Roefs",         "Pays-Bas", "GK", 5.5),
        p("Bart Verbruggen",     "Pays-Bas", "GK", 8.0),
        p("Nathan Aké",          "Pays-Bas", "DEF", 9.0),
        p("Denzel Dumfries",     "Pays-Bas", "DEF", 9.5),
        p("Jorrel Hato",         "Pays-Bas", "DEF", 8.5),
        p("Jurriën Timber",      "Pays-Bas", "DEF", 9.5),
        p("Micky van de Ven",    "Pays-Bas", "DEF", 9.0),
        p("Virgil van Dijk",     "Pays-Bas", "DEF", 11.0),
        p("Jan Paul van Hecke",  "Pays-Bas", "DEF", 7.5),
        p("Mats Wieffer",        "Pays-Bas", "DEF", 7.5),
        p("Frenkie de Jong",     "Pays-Bas", "MID", 10.5),
        p("Marten de Roon",      "Pays-Bas", "MID", 7.5),
        p("Ryan Gravenberch",    "Pays-Bas", "MID", 9.5),
        p("Justin Kluivert",     "Pays-Bas", "MID", 7.5),
        p("Teun Koopmeiners",    "Pays-Bas", "MID", 9.5),
        p("Tijjani Reijnders",   "Pays-Bas", "MID", 10.0),
        p("Guus Til",            "Pays-Bas", "MID", 7.0),
        p("Quinten Timber",      "Pays-Bas", "MID", 7.5),
        p("Brian Brobbey",       "Pays-Bas", "FWD", 8.0),
        p("Memphis Depay",       "Pays-Bas", "FWD", 8.5),
        p("Cody Gakpo",          "Pays-Bas", "FWD", 10.5),
        p("Noa Lang",            "Pays-Bas", "FWD", 8.5),
        p("Donyell Malen",       "Pays-Bas", "FWD", 8.0),
        p("Crysencio Summerville","Pays-Bas","FWD", 8.5),
        p("Wout Weghorst",       "Pays-Bas", "FWD", 7.5),
    ],
    "coaches": [],
},

"Japon": {
    "groupe": "F",
    "players": [
        p("Hayakawa Tomoki",    "Japon", "GK", 5.5),
        p("Suzuki Zion",        "Japon", "GK", 6.5),
        p("Osako Keisuke",      "Japon", "GK", 5.5),
        p("Nagatomo Yuto",      "Japon", "DEF", 6.5),
        p("Taniguchi Shogo",    "Japon", "DEF", 6.0),
        p("Tomiyasu Takehiro",  "Japon", "DEF", 8.5),
        p("Itakura Ko",         "Japon", "DEF", 8.0),
        p("Watanabe Tsuyoshi",  "Japon", "DEF", 7.0),
        p("Ito Hiroki",         "Japon", "DEF", 8.5),
        p("Suzuki Junnosuke",   "Japon", "DEF", 6.5),
        p("Seko Ayumu",         "Japon", "DEF", 6.5),
        p("Sugawara Yukinari",  "Japon", "DEF", 7.0),
        p("Kamada Daichi",      "Japon", "MID", 8.5),
        p("Sano Kaishu",        "Japon", "MID", 7.0),
        p("Tanaka Ao",          "Japon", "MID", 8.0),
        p("Endo Wataru",        "Japon", "MID", 9.0),
        p("Nakamura Keito",     "Japon", "MID", 7.5),
        p("Doan Ritsu",         "Japon", "FWD", 9.0),
        p("Ito Junya",          "Japon", "FWD", 8.5),
        p("Kubo Takefusa",      "Japon", "FWD", 10.5),
        p("Suzuki Yuito",       "Japon", "FWD", 7.5),
        p("Ueda Ayase",         "Japon", "FWD", 8.0),
        p("Ogawa Koki",         "Japon", "FWD", 7.0),
        p("Maeda Daizen",       "Japon", "FWD", 7.5),
        p("Shiogai Kento",      "Japon", "FWD", 7.0),
        p("Goto Keisuke",       "Japon", "FWD", 6.5),
    ],
    "coaches": [],
},

"Suède": {
    "groupe": "F",
    "players": [
        p("Viktor Johansson",        "Suède", "GK", 6.0),
        p("Kristoffer Nordfeldt",    "Suède", "GK", 5.5),
        p("Jacob Widell Zetterström","Suède", "GK", 5.5),
        p("Hjalmar Ekdal",           "Suède", "DEF", 6.5),
        p("Gabriel Gudmundsson",     "Suède", "DEF", 7.0),
        p("Isak Hien",               "Suède", "DEF", 8.0),
        p("Herman Johansson",        "Suède", "DEF", 5.5),
        p("Gustaf Lagerbielke",      "Suède", "DEF", 7.0),
        p("Victor Lindelöf",         "Suède", "DEF", 8.5),
        p("Eric Smith",              "Suède", "DEF", 6.5),
        p("Carl Starfelt",           "Suède", "DEF", 7.0),
        p("Elliot Stroud",           "Suède", "DEF", 5.0),
        p("Daniel Svensson",         "Suède", "DEF", 7.0),
        p("Jesper Kalström",         "Suède", "MID", 6.5),
        p("Yasin Ayari",             "Suède", "MID", 7.5),
        p("Mattias Svanberg",        "Suède", "MID", 7.5),
        p("Lucas Bergvall",          "Suède", "MID", 8.5),
        p("Besfort Zeneli",          "Suède", "MID", 6.0),
        p("Taha Ali",                "Suède", "FWD", 5.5),
        p("Alexander Bernhardsson",  "Suède", "FWD", 6.5),
        p("Anthony Elanga",          "Suède", "FWD", 8.5),
        p("Viktor Gyökeres",         "Suède", "FWD", 12.0),
        p("Alexander Isak",          "Suède", "FWD", 11.5),
        p("Gustaf Nilsson",          "Suède", "FWD", 7.0),
        p("Benjamin Nygren",         "Suède", "FWD", 6.5),
        p("Ken Sema",                "Suède", "FWD", 6.0),
    ],
    "coaches": [],
},

"Tunisie": {
    "groupe": "F",
    "players": [
        p("Sabri Ben Hessen",       "Tunisie", "GK", 5.0),
        p("Abdelmouhib Chamakh",    "Tunisie", "GK", 4.5),
        p("Aymen Dahman",           "Tunisie", "GK", 5.0),
        p("Ali Abdi",               "Tunisie", "DEF", 7.0),
        p("Adem Arous",             "Tunisie", "DEF", 5.5),
        p("Mohamed Amine Ben Hamida","Tunisie","DEF", 5.0),
        p("Dylan Bronn",            "Tunisie", "DEF", 7.0),
        p("Raed Chikhaoui",         "Tunisie", "DEF", 5.5),
        p("Moutaz Neffati",         "Tunisie", "DEF", 5.5),
        p("Omar Rekik",             "Tunisie", "DEF", 6.5),
        p("Montassar Talbi",        "Tunisie", "DEF", 7.0),
        p("Yan Valery",             "Tunisie", "DEF", 6.0),
        p("Mortadha Ben Ouanes",    "Tunisie", "MID", 6.0),
        p("Anis Ben Slimane",       "Tunisie", "MID", 7.5),
        p("Ismael Gharbi",          "Tunisie", "MID", 7.0),
        p("Rani Khedira",           "Tunisie", "MID", 7.5),
        p("Mohamed Hadj Mahmoud",   "Tunisie", "MID", 6.0),
        p("Hannibal Mejbri",        "Tunisie", "MID", 8.5),
        p("Ellyes Skhiri",          "Tunisie", "MID", 8.5),
        p("Elias Achouri",          "Tunisie", "FWD", 7.0),
        p("Khalil Ayari",           "Tunisie", "FWD", 7.5),
        p("Firas Chaouat",          "Tunisie", "FWD", 5.5),
        p("Rayan Elloumi",          "Tunisie", "FWD", 6.0),
        p("Hazem Mastouri",         "Tunisie", "FWD", 5.5),
        p("Elias Saad",             "Tunisie", "FWD", 6.5),
        p("Sebastian Tounekti",     "Tunisie", "FWD", 6.5),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE G ─────────────────────────────────────────
"Belgique": {
    "groupe": "G",
    "players": [
        p("Thibaut Courtois",       "Belgique", "GK", 12.0),
        p("Senne Lammens",          "Belgique", "GK", 7.0),
        p("Mike Penders",           "Belgique", "GK", 6.0),
        p("Timothy Castagne",       "Belgique", "DEF", 8.0),
        p("Zeno Debast",            "Belgique", "DEF", 8.5),
        p("Maxim De Cuyper",        "Belgique", "DEF", 8.0),
        p("Koni De Winter",         "Belgique", "DEF", 7.5),
        p("Brandon Mechele",        "Belgique", "DEF", 6.5),
        p("Thomas Meunier",         "Belgique", "DEF", 7.5),
        p("Nathan Ngoy",            "Belgique", "DEF", 7.0),
        p("Joaquin Seys",           "Belgique", "DEF", 6.5),
        p("Arthur Theate",          "Belgique", "DEF", 8.0),
        p("Kevin De Bruyne",        "Belgique", "MID", 11.5),
        p("Amadou Onana",           "Belgique", "MID", 9.5),
        p("Nicolas Raskin",         "Belgique", "MID", 7.5),
        p("Youri Tielemans",        "Belgique", "MID", 8.5),
        p("Hans Vanaken",           "Belgique", "MID", 8.0),
        p("Axel Witsel",            "Belgique", "MID", 7.5),
        p("Charles De Ketelaere",   "Belgique", "FWD", 9.5),
        p("Jeremy Doku",            "Belgique", "FWD", 10.0),
        p("Matias Fernandez Pardo", "Belgique", "FWD", 7.0),
        p("Romelu Lukaku",          "Belgique", "FWD", 10.5),
        p("Dodi Lukebakio",         "Belgique", "FWD", 8.0),
        p("Diego Moreira",          "Belgique", "FWD", 7.0),
        p("Alexis Saelemaekers",    "Belgique", "FWD", 8.5),
        p("Leandro Trossard",       "Belgique", "FWD", 9.5),
    ],
    "coaches": [],
},

"Égypte": {
    "groupe": "G",
    "players": [
        p("Mohamed El Shenawy",   "Égypte", "GK", 6.5),
        p("Mostafa Shobeir",      "Égypte", "GK", 5.5),
        p("Mohamed Alaa",         "Égypte", "GK", 4.5),
        p("Mohamed Hani",         "Égypte", "DEF", 6.5),
        p("Tarek Alaa",           "Égypte", "DEF", 5.5),
        p("Hamdy Fathy",          "Égypte", "DEF", 6.0),
        p("Rami Rabia",           "Égypte", "DEF", 6.0),
        p("Yasser Ibrahim",       "Égypte", "DEF", 7.0),
        p("Hossam Abdelmaguid",   "Égypte", "DEF", 6.0),
        p("Mohamed Abdelmonem",   "Égypte", "DEF", 7.5),
        p("Ahmed Fotouh",         "Égypte", "DEF", 5.5),
        p("Karim Hafez",          "Égypte", "DEF", 6.0),
        p("Marwan Attia",         "Égypte", "MID", 6.0),
        p("Mohanad Lasheen",      "Égypte", "MID", 6.0),
        p("Nabil Emad",           "Égypte", "MID", 5.5),
        p("Mahmoud Saber",        "Égypte", "MID", 5.5),
        p("Ahmed Zizo",           "Égypte", "MID", 7.0),
        p("Emam Ashour",          "Égypte", "MID", 7.0),
        p("Mostafa Ziko",         "Égypte", "MID", 6.0),
        p("Mahmoud Trezeguet",    "Égypte", "MID", 8.5),
        p("Ibrahim Adel",         "Égypte", "MID", 7.5),
        p("Haissem Hassan",       "Égypte", "MID", 6.5),
        p("Mohamed Salah",        "Égypte", "FWD", 12.0),
        p("Omar Marmoush",        "Égypte", "FWD", 11.0),
        p("Aqtay Abdallah",       "Égypte", "FWD", 5.0),
        p("Hamza Abdelkarim",     "Égypte", "FWD", 6.0),
    ],
    "coaches": [],
},

"Iran": {
    "groupe": "G",
    "players": [
        p("Alireza Beiranvand",       "Iran", "GK", 7.5),
        p("Seyed Hossein Hosseini",   "Iran", "GK", 6.0),
        p("Payam Niazmand",           "Iran", "GK", 5.0),
        p("Danial Eiri",              "Iran", "DEF", 5.5),
        p("Ehsan Hajsafi",            "Iran", "DEF", 7.0),
        p("Saleh Hardani",            "Iran", "DEF", 5.5),
        p("Hossein Kanaani",          "Iran", "DEF", 6.0),
        p("Shoja Khalilzadeh",        "Iran", "DEF", 6.5),
        p("Milad Mohammadi",          "Iran", "DEF", 6.5),
        p("Ali Nemati",               "Iran", "DEF", 5.5),
        p("Ramin Rezaeian",           "Iran", "DEF", 6.5),
        p("Rouzbeh Cheshmi",          "Iran", "MID", 6.5),
        p("Saeid Ezatolahi",          "Iran", "MID", 7.5),
        p("Mehdi Ghaedi",             "Iran", "MID", 7.0),
        p("Saman Ghoddos",            "Iran", "MID", 7.5),
        p("Mohammad Ghorbani",        "Iran", "MID", 6.0),
        p("Alireza Jahanbakhsh",      "Iran", "MID", 8.0),
        p("Mohammad Mohebi",          "Iran", "MID", 6.0),
        p("Amir Mohammad Razzaghinia","Iran", "MID", 5.5),
        p("Mehdi Torabi",             "Iran", "MID", 7.0),
        p("Aria Yousefi",             "Iran", "MID", 5.5),
        p("Ali Alipour",              "Iran", "FWD", 7.0),
        p("Dennis Dargahi",           "Iran", "FWD", 6.5),
        p("Amirhossein Hosseinzadeh", "Iran", "FWD", 6.5),
        p("Mehdi Taremi",             "Iran", "FWD", 10.5),
        p("Shahriyar Moghanlou",      "Iran", "FWD", 5.5),
    ],
    "coaches": [],
},

"Nouvelle-Zélande": {
    "groupe": "G",
    "players": [
        p("Max Crocombe",        "Nouvelle-Zélande", "GK", 6.0),
        p("Alex Paulsen",        "Nouvelle-Zélande", "GK", 5.0),
        p("Michael Woud",        "Nouvelle-Zélande", "GK", 5.0),
        p("Tim Payne",           "Nouvelle-Zélande", "DEF", 5.5),
        p("Francis De Vries",    "Nouvelle-Zélande", "DEF", 5.0),
        p("Tyler Bindon",        "Nouvelle-Zélande", "DEF", 7.0),
        p("Michael Boxall",      "Nouvelle-Zélande", "DEF", 6.0),
        p("Liberato Cacace",     "Nouvelle-Zélande", "DEF", 6.5),
        p("Nando Pijnaker",      "Nouvelle-Zélande", "DEF", 5.5),
        p("Finn Surman",         "Nouvelle-Zélande", "DEF", 5.5),
        p("Callan Elliot",       "Nouvelle-Zélande", "DEF", 5.5),
        p("Tommy Smith",         "Nouvelle-Zélande", "DEF", 5.5),
        p("Joe Bell",            "Nouvelle-Zélande", "MID", 6.0),
        p("Marko Stamenić",      "Nouvelle-Zélande", "MID", 6.5),
        p("Alex Rufer",          "Nouvelle-Zélande", "MID", 5.5),
        p("Ryan Thomas",         "Nouvelle-Zélande", "MID", 6.0),
        p("Lachlan Bayliss",     "Nouvelle-Zélande", "MID", 5.0),
        p("Matt Garbett",        "Nouvelle-Zélande", "FWD", 6.0),
        p("Chris Wood",          "Nouvelle-Zélande", "FWD", 9.0),
        p("Sarpreet Singh",      "Nouvelle-Zélande", "FWD", 6.0),
        p("Eli Just",            "Nouvelle-Zélande", "FWD", 5.5),
        p("Kosta Barbarouses",   "Nouvelle-Zélande", "FWD", 5.5),
        p("Ben Waine",           "Nouvelle-Zélande", "FWD", 5.5),
        p("Ben Old",             "Nouvelle-Zélande", "FWD", 6.0),
        p("Callum McCowatt",     "Nouvelle-Zélande", "FWD", 5.5),
        p("Jesse Randall",       "Nouvelle-Zélande", "FWD", 5.0),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE H ─────────────────────────────────────────
"Espagne": {
    "groupe": "H",
    "players": [
        p("Unai Simón",          "Espagne", "GK", 9.5),
        p("David Raya",          "Espagne", "GK", 9.0),
        p("Joan Garcia",         "Espagne", "GK", 7.0),
        p("Marc Cucurella",      "Espagne", "DEF", 9.0),
        p("Alejandro Grimaldo",  "Espagne", "DEF", 9.5),
        p("Pau Cubarsí",         "Espagne", "DEF", 9.5),
        p("Aymeric Laporte",     "Espagne", "DEF", 8.5),
        p("Marc Pubill",         "Espagne", "DEF", 7.5),
        p("Eric García",         "Espagne", "DEF", 8.0),
        p("Marcos Llorente",     "Espagne", "DEF", 8.0),
        p("Pedro Porro",         "Espagne", "DEF", 8.5),
        p("Pedri",               "Espagne", "MID", 11.5),
        p("Fabián Ruiz",         "Espagne", "MID", 10.0),
        p("Martín Zubimendi",    "Espagne", "MID", 9.5),
        p("Gavi",                "Espagne", "MID", 11.0),
        p("Rodri",               "Espagne", "MID", 12.0),
        p("Álex Baena",          "Espagne", "MID", 8.5),
        p("Mikel Merino",        "Espagne", "MID", 9.0),
        p("Mikel Oyarzabal",     "Espagne", "FWD", 9.5),
        p("Dani Olmo",           "Espagne", "FWD", 10.5),
        p("Nico Williams",       "Espagne", "FWD", 10.5),
        p("Yéremy Pino",         "Espagne", "FWD", 8.5),
        p("Ferran Torres",       "Espagne", "FWD", 8.5),
        p("Borja Iglesias",      "Espagne", "FWD", 7.0),
        p("Víctor Muñoz",        "Espagne", "FWD", 6.5),
        p("Lamine Yamal",        "Espagne", "FWD", 12.0),
    ],
    "coaches": [],
},

"Cap-Vert": {
    "groupe": "H",
    "players": [
        p("Josimar Dias",       "Cap-Vert", "GK", 5.5),
        p("Márcio da Rosa",     "Cap-Vert", "GK", 5.0),
        p("Carlos Santos",      "Cap-Vert", "GK", 5.0),
        p("Steven Moreira",     "Cap-Vert", "DEF", 6.0),
        p("Wagner Pina",        "Cap-Vert", "DEF", 5.5),
        p("João Paulo Fernandes","Cap-Vert","DEF", 6.0),
        p("Sidny Lopes Cabral", "Cap-Vert", "DEF", 7.5),
        p("Logan Costa",        "Cap-Vert", "DEF", 8.0),
        p("Roberto Lopes",      "Cap-Vert", "DEF", 6.0),
        p("Kelvin Pires",       "Cap-Vert", "DEF", 5.5),
        p("Ianique Tavares",    "Cap-Vert", "DEF", 5.5),
        p("Edilson Borges",     "Cap-Vert", "DEF", 5.5),
        p("Jamiro Monteiro",    "Cap-Vert", "MID", 6.5),
        p("Telmo Arcanjo",      "Cap-Vert", "MID", 6.0),
        p("Yannick Semedo",     "Cap-Vert", "MID", 6.0),
        p("Laros Duarte",       "Cap-Vert", "MID", 7.0),
        p("Deroy Duarte",       "Cap-Vert", "MID", 6.5),
        p("Kevin Pina",         "Cap-Vert", "MID", 6.0),
        p("Ryan Mendes",        "Cap-Vert", "FWD", 6.5),
        p("Willy Semedo",       "Cap-Vert", "FWD", 6.0),
        p("Garry Rodrigues",    "Cap-Vert", "FWD", 7.0),
        p("Jovane Cabral",      "Cap-Vert", "FWD", 7.5),
        p("Nuno Da Costa",      "Cap-Vert", "FWD", 7.0),
        p("Dailon Livramento",  "Cap-Vert", "FWD", 6.5),
        p("Gilson Benchimol",   "Cap-Vert", "FWD", 5.5),
        p("Hélio Varela",       "Cap-Vert", "FWD", 5.5),
    ],
    "coaches": [],
},

"Arabie saoudite": {
    "groupe": "H",
    "players": [
        p("Nawaf Al Aqidi",        "Arabie saoudite", "GK", 6.0),
        p("Mohamed Al Owais",      "Arabie saoudite", "GK", 7.0),
        p("Ahmed Alkassar",        "Arabie saoudite", "GK", 5.5),
        p("Saud Abdulhamid",       "Arabie saoudite", "DEF", 7.5),
        p("Jehad Thakri",          "Arabie saoudite", "DEF", 6.0),
        p("Abdulelah Al Amri",     "Arabie saoudite", "DEF", 6.5),
        p("Hassan Tambakti",       "Arabie saoudite", "DEF", 7.0),
        p("Ali Lajami",            "Arabie saoudite", "DEF", 6.5),
        p("Hassan Kadesh",         "Arabie saoudite", "DEF", 6.5),
        p("Moteb Al Harbi",        "Arabie saoudite", "DEF", 6.5),
        p("Nawaf Boushal",         "Arabie saoudite", "DEF", 6.5),
        p("Ali Majrashi",          "Arabie saoudite", "DEF", 6.0),
        p("Mohammed Abu Alshamat", "Arabie saoudite", "DEF", 6.0),
        p("Ziyad Al Johani",       "Arabie saoudite", "MID", 6.5),
        p("Nasser Al Dawsari",     "Arabie saoudite", "MID", 8.0),
        p("Mohamed Kanno",         "Arabie saoudite", "MID", 7.5),
        p("Abdullah Al Khaibari",  "Arabie saoudite", "MID", 7.0),
        p("Alaa Al Hejji",         "Arabie saoudite", "MID", 6.0),
        p("Musab Al Juwayr",       "Arabie saoudite", "MID", 7.0),
        p("Sultan Mandash",        "Arabie saoudite", "MID", 7.0),
        p("Ayman Yahya",           "Arabie saoudite", "MID", 6.5),
        p("Khalid Al Ghannam",     "Arabie saoudite", "MID", 6.5),
        p("Salem Al Dawsari",      "Arabie saoudite", "FWD", 9.0),
        p("Abdullah Al Hamdan",    "Arabie saoudite", "FWD", 7.5),
        p("Feras Al Brikan",       "Arabie saoudite", "FWD", 7.0),
        p("Saleh Al Shehri",       "Arabie saoudite", "FWD", 7.5),
    ],
    "coaches": [],
},

"Uruguay": {
    "groupe": "H",
    "players": [
        p("Sergio Rochet",         "Uruguay", "GK", 7.5),
        p("Fernando Muslera",      "Uruguay", "GK", 7.0),
        p("Santiago Mele",         "Uruguay", "GK", 6.0),
        p("Guillermo Varela",      "Uruguay", "DEF", 7.0),
        p("Ronald Araujo",         "Uruguay", "DEF", 11.0),
        p("José María Giménez",    "Uruguay", "DEF", 9.0),
        p("Santiago Bueno",        "Uruguay", "DEF", 8.0),
        p("Sebastián Cáceres",     "Uruguay", "DEF", 7.0),
        p("Mathías Olivera",       "Uruguay", "DEF", 8.5),
        p("Joaquín Piquerez",      "Uruguay", "DEF", 7.5),
        p("Matías Viña",           "Uruguay", "DEF", 7.0),
        p("Manuel Ugarte",         "Uruguay", "MID", 10.5),
        p("Emiliano Martínez",     "Uruguay", "MID", 7.0),
        p("Rodrigo Bentancur",     "Uruguay", "MID", 9.0),
        p("Federico Valverde",     "Uruguay", "MID", 11.5),
        p("Agustín Canobbio",      "Uruguay", "MID", 7.0),
        p("Juan Manuel Sanabria",  "Uruguay", "MID", 6.0),
        p("Giorgan de Arrascaeta", "Uruguay", "MID", 9.0),
        p("Nicolás de la Cruz",    "Uruguay", "MID", 8.5),
        p("Rodrigo Zalazar",       "Uruguay", "MID", 7.0),
        p("Facundo Pellistri",     "Uruguay", "FWD", 7.5),
        p("Maximiliano Araújo",    "Uruguay", "FWD", 7.5),
        p("Brian Rodríguez",       "Uruguay", "FWD", 7.5),
        p("Rodrigo Aguirre",       "Uruguay", "FWD", 7.0),
        p("Federico Viñas",        "Uruguay", "FWD", 6.5),
        p("Darwin Núñez",          "Uruguay", "FWD", 11.5),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE I ─────────────────────────────────────────
"France": {
    "groupe": "I",
    "players": [
        p("Mike Maignan",          "France", "GK", 11.0),
        p("Brice Samba",           "France", "GK", 7.5),
        p("Robin Risser",          "France", "GK", 6.0),
        p("Dayot Upamecano",       "France", "DEF", 9.5),
        p("William Saliba",        "France", "DEF", 11.0),
        p("Lucas Digne",           "France", "DEF", 7.5),
        p("Theo Hernandez",        "France", "DEF", 10.5),
        p("Lucas Hernandez",       "France", "DEF", 8.5),
        p("Ibrahima Konaté",       "France", "DEF", 9.5),
        p("Jules Koundé",          "France", "DEF", 10.5),
        p("Malo Gusto",            "France", "DEF", 8.0),
        p("Maxence Lacroix",       "France", "DEF", 7.5),
        p("N'Golo Kanté",          "France", "MID", 10.0),
        p("Adrien Rabiot",         "France", "MID", 8.5),
        p("Manu Koné",             "France", "MID", 8.5),
        p("Aurélien Tchouaméni",   "France", "MID", 10.5),
        p("Warren Zaïre-Emery",    "France", "MID", 9.5),
        p("Maghnes Akliouche",     "France", "FWD", 8.5),
        p("Kylian Mbappé",         "France", "FWD", 12.0),
        p("Ousmane Dembélé",       "France", "FWD", 11.5),
        p("Michael Olise",         "France", "FWD", 10.5),
        p("Désiré Doué",           "France", "FWD", 9.0),
        p("Bradley Barcola",       "France", "FWD", 9.5),
        p("Rayan Cherki",          "France", "FWD", 9.0),
        p("Marcus Thuram",         "France", "FWD", 10.5),
        p("Jean-Philippe Mateta",  "France", "FWD", 8.0),
    ],
    "coaches": [],
},

"Sénégal": {
    "groupe": "I",
    "players": [
        p("Édouard Mendy",        "Sénégal", "GK", 9.0),
        p("Mory Diaw",            "Sénégal", "GK", 6.0),
        p("Yehvann Diouf",        "Sénégal", "GK", 6.5),
        p("Krépin Diatta",        "Sénégal", "DEF", 8.0),
        p("Antoine Mendy",        "Sénégal", "DEF", 7.0),
        p("Kalidou Koulibaly",    "Sénégal", "DEF", 10.5),
        p("El Hadji Malick Diouf","Sénégal", "DEF", 8.0),
        p("Mamadou Sarr",         "Sénégal", "DEF", 7.5),
        p("Moussa Niakhaté",      "Sénégal", "DEF", 8.0),
        p("Abdoulaye Seck",       "Sénégal", "DEF", 6.0),
        p("Ismaïl Jakobs",        "Sénégal", "DEF", 7.0),
        p("Idrissa Gana Gueye",   "Sénégal", "MID", 9.0),
        p("Pape Gueye",           "Sénégal", "MID", 7.5),
        p("Lamine Camara",        "Sénégal", "MID", 8.5),
        p("Habib Diarra",         "Sénégal", "MID", 7.5),
        p("Pathé Ciss",           "Sénégal", "MID", 7.0),
        p("Pape Matar Sarr",      "Sénégal", "MID", 9.0),
        p("Bara Sapoko Ndiaye",   "Sénégal", "MID", 9.0),
        p("Sadio Mané",           "Sénégal", "FWD", 11.0),
        p("Ismaïla Sarr",         "Sénégal", "FWD", 9.0),
        p("Iliman Ndiaye",        "Sénégal", "FWD", 8.5),
        p("Assane Diao",          "Sénégal", "FWD", 7.5),
        p("Ibrahim Mbaye",        "Sénégal", "FWD", 7.0),
        p("Nicolas Jackson",      "Sénégal", "FWD", 9.5),
        p("Bamba Dieng",          "Sénégal", "FWD", 7.0),
        p("Chérif Ndiaye",        "Sénégal", "FWD", 6.5),
    ],
    "coaches": [],
},

"Norvège": {
    "groupe": "I",
    "players": [
        p("Ørjan Nyland",            "Norvège", "GK", 7.0),
        p("Egil Selvik",             "Norvège", "GK", 5.5),
        p("Sander Tangvik",          "Norvège", "GK", 5.5),
        p("Julian Ryerson",          "Norvège", "DEF", 7.5),
        p("Kristoffer Ajer",         "Norvège", "DEF", 8.0),
        p("Leo Skiri Østigård",      "Norvège", "DEF", 7.5),
        p("David Møller Wolfe",      "Norvège", "DEF", 7.0),
        p("Marcus Holmgren Pedersen","Norvège", "DEF", 7.0),
        p("Torbjørn Heggem",         "Norvège", "DEF", 7.0),
        p("Fredrik Bjørkan",         "Norvège", "DEF", 6.5),
        p("Henrik Falchener",        "Norvège", "DEF", 6.0),
        p("Sondre Langås",           "Norvège", "DEF", 6.0),
        p("Martin Ødegaard",         "Norvège", "MID", 12.0),
        p("Sander Berge",            "Norvège", "MID", 8.5),
        p("Patrick Berg",            "Norvège", "MID", 7.5),
        p("Kristian Thorstvedt",     "Norvège", "MID", 7.5),
        p("Morten Thorsby",          "Norvège", "MID", 7.0),
        p("Thelo Aasgaard",          "Norvège", "MID", 7.0),
        p("Andreas Schjelderup",     "Norvège", "MID", 8.0),
        p("Jens Petter Hauge",       "Norvège", "MID", 7.5),
        p("Fredrik Aursnes",         "Norvège", "MID", 8.0),
        p("Erling Haaland",          "Norvège", "FWD", 12.0),
        p("Alexander Sørloth",       "Norvège", "FWD", 9.5),
        p("Jørgen Strand Larsen",    "Norvège", "FWD", 8.5),
        p("Oscar Bobb",              "Norvège", "FWD", 8.0),
        p("Antonio Nusa",            "Norvège", "FWD", 8.5),
    ],
    "coaches": [],
},

"Irak": {
    "groupe": "I",
    "players": [
        p("Fahad Talib",       "Irak", "GK", 5.5),
        p("Jalal Hassan",      "Irak", "GK", 5.0),
        p("Ahmed Basil",       "Irak", "GK", 4.5),
        p("Hussein Ali",       "Irak", "DEF", 6.5),
        p("Manaf Younis",      "Irak", "DEF", 5.5),
        p("Zaid Tahseen",      "Irak", "DEF", 5.5),
        p("Rebin Sulaka",      "Irak", "DEF", 5.0),
        p("Akam Hashem",       "Irak", "DEF", 5.5),
        p("Merchas Doski",     "Irak", "DEF", 6.5),
        p("Ahmed Yahya",       "Irak", "DEF", 5.5),
        p("Zaid Ismail",       "Irak", "DEF", 5.5),
        p("Frans Putros",      "Irak", "DEF", 6.0),
        p("Mustafa Saadoon",   "Irak", "DEF", 5.5),
        p("Amir Al-Ammari",    "Irak", "MID", 6.0),
        p("Kevin Yakob",       "Irak", "MID", 6.5),
        p("Zidane Iqbal",      "Irak", "MID", 7.5),
        p("Aimar Sher",        "Irak", "MID", 6.0),
        p("Ibrahim Bayesh",    "Irak", "MID", 5.5),
        p("Ahmed Qasem",       "Irak", "MID", 6.5),
        p("Youssef Amyn",      "Irak", "MID", 6.5),
        p("Marko Farji",       "Irak", "MID", 6.0),
        p("Ali Jassim",        "Irak", "FWD", 7.5),
        p("Ali Al-Hamadi",     "Irak", "FWD", 8.0),
        p("Ali Youssef",       "Irak", "FWD", 6.5),
        p("Aymen Hussein",     "Irak", "FWD", 6.5),
        p("Mohanad Ali",       "Irak", "FWD", 6.0),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE J ─────────────────────────────────────────
"Argentine": {
    "groupe": "J",
    "players": [
        p("Emiliano Martínez",   "Argentine", "GK", 11.5),
        p("Gerónimo Rulli",      "Argentine", "GK", 7.0),
        p("Juan Musso",          "Argentine", "GK", 7.5),
        p("Gonzalo Montiel",     "Argentine", "DEF", 7.5),
        p("Nahuel Molina",       "Argentine", "DEF", 9.0),
        p("Lisandro Martínez",   "Argentine", "DEF", 10.0),
        p("Nicolás Otamendi",    "Argentine", "DEF", 9.0),
        p("Leonardo Balerdi",    "Argentine", "DEF", 8.0),
        p("Cristian Romero",     "Argentine", "DEF", 10.5),
        p("Facundo Medina",      "Argentine", "DEF", 8.0),
        p("Nicolás Tagliafico",  "Argentine", "DEF", 8.0),
        p("Leandro Paredes",     "Argentine", "MID", 8.5),
        p("Rodrigo De Paul",     "Argentine", "MID", 10.5),
        p("Exequiel Palacios",   "Argentine", "MID", 9.0),
        p("Enzo Fernández",      "Argentine", "MID", 11.0),
        p("Alexis Mac Allister", "Argentine", "MID", 10.5),
        p("Giovani Lo Celso",    "Argentine", "MID", 8.5),
        p("Valentín Barco",      "Argentine", "MID", 7.0),
        p("Lionel Messi",        "Argentine", "FWD", 12.0),
        p("Nicolás Paz",         "Argentine", "FWD", 7.5),
        p("Thiago Almada",       "Argentine", "FWD", 8.0),
        p("Nicolás González",    "Argentine", "FWD", 8.5),
        p("Giuliano Simeone",    "Argentine", "FWD", 8.0),
        p("Lautaro Martínez",    "Argentine", "FWD", 11.5),
        p("José Manuel López",   "Argentine", "FWD", 7.0),
        p("Julián Álvarez",      "Argentine", "FWD", 11.0),
    ],
    "coaches": [],
},

"Algérie": {
    "groupe": "J",
    "players": [
        p("Luca Zidane",          "Algérie", "GK", 6.5),
        p("Oussama Benbot",       "Algérie", "GK", 5.0),
        p("Melvin Mastil",        "Algérie", "GK", 5.0),
        p("Rafik Belghali",       "Algérie", "DEF", 6.5),
        p("Samir Chergui",        "Algérie", "DEF", 6.0),
        p("Rayan Aït-Nouri",      "Algérie", "DEF", 9.5),
        p("Jaouen Hadjam",        "Algérie", "DEF", 7.0),
        p("Aïssa Mandi",          "Algérie", "DEF", 8.0),
        p("Ramy Bensebaïni",      "Algérie", "DEF", 9.0),
        p("Zineddine Belaïd",     "Algérie", "DEF", 5.5),
        p("Achref Abada",         "Algérie", "DEF", 5.5),
        p("Mohamed Amine Tougaï", "Algérie", "DEF", 6.0),
        p("Nabil Bentaleb",       "Algérie", "MID", 7.5),
        p("Hicham Boudaoui",      "Algérie", "MID", 8.0),
        p("Houssem Aouar",        "Algérie", "MID", 8.0),
        p("Farès Chaïbi",         "Algérie", "MID", 8.5),
        p("Ibrahim Maza",         "Algérie", "MID", 9.0),
        p("Yacine Titraoui",      "Algérie", "MID", 6.5),
        p("Ramiz Zerrouki",       "Algérie", "MID", 7.5),
        p("Mohamed Amoura",       "Algérie", "FWD", 9.5),
        p("Nadhir Benbouali",     "Algérie", "FWD", 6.5),
        p("Adil Boulbina",        "Algérie", "FWD", 6.0),
        p("Farès Ghedjemis",      "Algérie", "FWD", 7.0),
        p("Amine Gouiri",         "Algérie", "FWD", 9.0),
        p("Anis Hadj Moussa",     "Algérie", "FWD", 8.5),
        p("Riyad Mahrez",         "Algérie", "FWD", 11.0),
    ],
    "coaches": [],
},

"Autriche": {
    "groupe": "J",
    "players": [
        p("Patrick Pentz",          "Autriche", "GK", 7.0),
        p("Alexander Schlager",     "Autriche", "GK", 7.5),
        p("Florian Wiegele",        "Autriche", "GK", 5.5),
        p("David Affengruber",      "Autriche", "DEF", 5.5),
        p("David Alaba",            "Autriche", "DEF", 10.5),
        p("Kevin Danso",            "Autriche", "DEF", 8.5),
        p("Marco Friedl",           "Autriche", "DEF", 7.5),
        p("Philipp Lienhart",       "Autriche", "DEF", 7.5),
        p("Phillipp Mwene",         "Autriche", "DEF", 6.5),
        p("Stefan Posch",           "Autriche", "DEF", 7.5),
        p("Alexander Prass",        "Autriche", "DEF", 7.5),
        p("Michael Svoboda",        "Autriche", "DEF", 7.0),
        p("Christoph Baumgartner",  "Autriche", "MID", 8.5),
        p("Carney Chukwuemeka",     "Autriche", "MID", 8.0),
        p("Florian Grillitsch",     "Autriche", "MID", 7.5),
        p("Konrad Laimer",          "Autriche", "MID", 9.0),
        p("Marcel Sabitzer",        "Autriche", "MID", 9.0),
        p("Xaver Schlager",         "Autriche", "MID", 8.5),
        p("Nicolas Seiwald",        "Autriche", "MID", 8.0),
        p("Romano Schmid",          "Autriche", "MID", 7.5),
        p("Alessandro Schöpf",      "Autriche", "MID", 6.5),
        p("Paul Wanner",            "Autriche", "MID", 7.0),
        p("Patrick Wimmer",         "Autriche", "FWD", 7.5),
        p("Marko Arnautović",       "Autriche", "FWD", 9.0),
        p("Michael Gregoritsch",    "Autriche", "FWD", 8.0),
        p("Sasa Kalajdzic",         "Autriche", "FWD", 7.5),
    ],
    "coaches": [],
},

"Jordanie": {
    "groupe": "J",
    "players": [
        p("Yazid Abulaila",       "Jordanie", "GK", 5.0),
        p("Abdallah Al Fakhouri", "Jordanie", "GK", 4.5),
        p("Nour Bani Attiah",     "Jordanie", "GK", 4.5),
        p("Mohammad Abualnadi",   "Jordanie", "DEF", 5.5),
        p("Husam Abu Dahab",      "Jordanie", "DEF", 5.0),
        p("Mohammad Abu Hashish", "Jordanie", "DEF", 5.0),
        p("Yazan Al Arab",        "Jordanie", "DEF", 5.5),
        p("Abdallah Nasib",       "Jordanie", "DEF", 5.5),
        p("Saleem Obaid",         "Jordanie", "DEF", 5.0),
        p("Ehsan Haddad",         "Jordanie", "DEF", 5.0),
        p("Saed Al-Rosan",        "Jordanie", "DEF", 5.5),
        p("Anas Banawi",          "Jordanie", "DEF", 5.5),
        p("Mohannad Abu Taha",    "Jordanie", "DEF", 5.5),
        p("Mohammad Al Dawoud",   "Jordanie", "MID", 5.5),
        p("Nizar Al Rashdan",     "Jordanie", "MID", 5.5),
        p("Noor Al Rawabdeh",     "Jordanie", "MID", 5.5),
        p("Rajaei Ayed",          "Jordanie", "MID", 5.0),
        p("Amer Jamous",          "Jordanie", "MID", 5.5),
        p("Ibrahim Sadeh",        "Jordanie", "MID", 5.0),
        p("Mahmoud Al-Mardi",     "Jordanie", "MID", 5.5),
        p("Mousa Al Tamari",      "Jordanie", "FWD", 8.5),
        p("Odeh Al-Fakhouri",     "Jordanie", "FWD", 6.0),
        p("Mohammad Abu Zrayq",   "Jordanie", "FWD", 6.5),
        p("Ali Azaizeh",          "Jordanie", "FWD", 6.0),
        p("Ali Olwan",            "Jordanie", "FWD", 5.5),
        p("Ibrahim Sabra",        "Jordanie", "FWD", 6.0),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE K ─────────────────────────────────────────
"Portugal": {
    "groupe": "K",
    "players": [
        p("Diogo Costa",          "Portugal", "GK", 10.0),
        p("José Sá",              "Portugal", "GK", 7.5),
        p("Rui Silva",            "Portugal", "GK", 6.5),
        p("Diogo Dalot",          "Portugal", "DEF", 9.0),
        p("Matheus Nunes",        "Portugal", "DEF", 9.0),
        p("Nélson Semedo",        "Portugal", "DEF", 8.0),
        p("João Cancelo",         "Portugal", "DEF", 10.0),
        p("Nuno Mendes",          "Portugal", "DEF", 10.0),
        p("Gonçalo Inácio",       "Portugal", "DEF", 8.5),
        p("Renato Veiga",         "Portugal", "DEF", 8.5),
        p("Rúben Dias",           "Portugal", "DEF", 11.5),
        p("Tomás Araújo",         "Portugal", "DEF", 7.5),
        p("Rúben Neves",          "Portugal", "MID", 9.5),
        p("Samuel Costa",         "Portugal", "MID", 7.0),
        p("João Neves",           "Portugal", "MID", 10.0),
        p("Vitinha",              "Portugal", "MID", 10.0),
        p("Bruno Fernandes",      "Portugal", "MID", 11.0),
        p("Bernardo Silva",       "Portugal", "MID", 11.5),
        p("João Félix",           "Portugal", "FWD", 9.5),
        p("Francisco Trincão",    "Portugal", "FWD", 8.0),
        p("Francisco Conceição",  "Portugal", "FWD", 9.0),
        p("Pedro Neto",           "Portugal", "FWD", 9.5),
        p("Rafael Leão",          "Portugal", "FWD", 11.0),
        p("Gonçalo Guedes",       "Portugal", "FWD", 8.0),
        p("Gonçalo Ramos",        "Portugal", "FWD", 10.0),
        p("Cristiano Ronaldo",    "Portugal", "FWD", 11.0),
    ],
    "coaches": [],
},

"RD Congo": {
    "groupe": "K",
    "players": [
        p("Timothy Fayulu",        "RD Congo", "GK", 5.5),
        p("Lionel Mpasi",          "RD Congo", "GK", 6.0),
        p("Mike Epolo",            "RD Congo", "GK", 6.0),
        p("Aaron Wan-Bissaka",     "RD Congo", "DEF", 8.0),
        p("Gédéon Kalulu",         "RD Congo", "DEF", 6.0),
        p("Joris Kayembe",         "RD Congo", "DEF", 6.5),
        p("Arthur Masuaku",        "RD Congo", "DEF", 7.5),
        p("Steve Kapuadi",         "RD Congo", "DEF", 6.0),
        p("Rocky Bushiri",         "RD Congo", "DEF", 6.0),
        p("Axel Tuanzebe",         "RD Congo", "DEF", 6.5),
        p("Chancel Mbemba",        "RD Congo", "DEF", 8.0),
        p("Dylan Batubinsika",     "RD Congo", "DEF", 6.0),
        p("Noah Sadiki",           "RD Congo", "MID", 7.5),
        p("Samuel Moutoussamy",    "RD Congo", "MID", 6.0),
        p("Edo Kayembe",           "RD Congo", "MID", 6.5),
        p("Nathan Mukau",          "RD Congo", "MID", 7.0),
        p("Charles Pickel",        "RD Congo", "MID", 6.5),
        p("Ngal'ayel Mukau Mbuku", "RD Congo", "MID", 7.0),
        p("Brian Cipenga",         "RD Congo", "MID", 6.0),
        p("Théo Bongonda",         "RD Congo", "MID", 7.5),
        p("Gaël Kakuta",           "RD Congo", "MID", 7.0),
        p("Meschack Elia",         "RD Congo", "FWD", 8.0),
        p("Fiston Mayele",         "RD Congo", "FWD", 7.5),
        p("Cédric Bakambu",        "RD Congo", "FWD", 8.5),
        p("Simon Banza",           "RD Congo", "FWD", 8.5),
        p("Yoane Wissa",           "RD Congo", "FWD", 9.5),
    ],
    "coaches": [],
},

"Ouzbékistan": {
    "groupe": "K",
    "players": [
        p("Utkir Yusupov",         "Ouzbékistan", "GK", 5.5),
        p("Abduvohid Nematov",     "Ouzbékistan", "GK", 5.0),
        p("Botirali Ergashev",     "Ouzbékistan", "GK", 5.0),
        p("Rustam Ashurmatov",     "Ouzbékistan", "DEF", 7.5),
        p("Farrukh Sayfiev",       "Ouzbékistan", "DEF", 6.5),
        p("Khojiakbar Alijonov",   "Ouzbékistan", "DEF", 6.0),
        p("Sherzod Nasrullaev",    "Ouzbékistan", "DEF", 6.0),
        p("Umar Eshmurodov",       "Ouzbékistan", "DEF", 6.5),
        p("Abdukodir Khusanov",    "Ouzbékistan", "DEF", 9.0),
        p("Abdulla Abdullaev",     "Ouzbékistan", "DEF", 6.0),
        p("Bekhruz Karimov",       "Ouzbékistan", "DEF", 6.0),
        p("Jakhongir Urozov",      "Ouzbékistan", "DEF", 6.0),
        p("Avazbek Ulmasaliev",    "Ouzbékistan", "DEF", 5.5),
        p("Otabek Shukurov",       "Ouzbékistan", "MID", 7.0),
        p("Jaloliddin Masharipov", "Ouzbékistan", "MID", 7.5),
        p("Odiljon Hamrobekov",    "Ouzbékistan", "MID", 7.0),
        p("Oston Urunov",          "Ouzbékistan", "MID", 7.5),
        p("Jamshid Iskanderov",    "Ouzbékistan", "MID", 6.5),
        p("Dostonbek Khamdamov",   "Ouzbékistan", "MID", 6.5),
        p("Abbosbek Fayzullaev",   "Ouzbékistan", "MID", 8.5),
        p("Akmal Mozgovoy",        "Ouzbékistan", "MID", 6.5),
        p("Azizjon Ganiev",        "Ouzbékistan", "MID", 6.5),
        p("Sherzod Esanov",        "Ouzbékistan", "MID", 6.0),
        p("Eldor Shomurodov",      "Ouzbékistan", "FWD", 9.5),
        p("Igor Sergeev",          "Ouzbékistan", "FWD", 7.0),
        p("Azizbek Amonov",        "Ouzbékistan", "FWD", 6.0),
    ],
    "coaches": [],
},

"Colombie": {
    "groupe": "K",
    "players": [
        p("Camilo Vargas",         "Colombie", "GK", 7.0),
        p("David Ospina",          "Colombie", "GK", 8.0),
        p("Álvaro Montero",        "Colombie", "GK", 6.0),
        p("Johan Mojica",          "Colombie", "DEF", 7.5),
        p("Deiver Machado",        "Colombie", "DEF", 7.0),
        p("Daniel Muñoz",          "Colombie", "DEF", 8.5),
        p("Santiago Arias",        "Colombie", "DEF", 7.0),
        p("Yerry Mina",            "Colombie", "DEF", 8.0),
        p("Davinson Sánchez",      "Colombie", "DEF", 8.5),
        p("Jhon Lucumí",           "Colombie", "DEF", 8.0),
        p("Willer Ditta",          "Colombie", "DEF", 6.5),
        p("James Rodríguez",       "Colombie", "MID", 10.0),
        p("Jefferson Lerma",       "Colombie", "MID", 8.5),
        p("Richard Ríos",          "Colombie", "MID", 8.5),
        p("Juan Fernando Quintero","Colombie", "MID", 8.5),
        p("Jorge Carrascal",       "Colombie", "MID", 7.5),
        p("Kevin Castaño",         "Colombie", "MID", 7.0),
        p("Jaminton Campaz",       "Colombie", "MID", 7.0),
        p("Luis Díaz",             "Colombie", "FWD", 11.5),
        p("Carlos Andrés Gómez",   "Colombie", "FWD", 6.5),
        p("Jhon Córdoba",          "Colombie", "FWD", 7.5),
        p("Juan Camilo Hernández", "Colombie", "FWD", 9.0),
        p("Jhon Arias",            "Colombie", "FWD", 8.5),
    ],
    "coaches": [],
},

# ────────────────────────── GROUPE L ─────────────────────────────────────────
"Angleterre": {
    "groupe": "L",
    "players": [
        p("Jordan Pickford",      "Angleterre", "GK", 9.5),
        p("Dean Henderson",       "Angleterre", "GK", 7.5),
        p("James Trafford",       "Angleterre", "GK", 7.0),
        p("Reece James",          "Angleterre", "DEF", 9.5),
        p("Tino Livramento",      "Angleterre", "DEF", 8.0),
        p("Marc Guéhi",           "Angleterre", "DEF", 9.0),
        p("Ezri Konsa",           "Angleterre", "DEF", 8.5),
        p("John Stones",          "Angleterre", "DEF", 10.0),
        p("Jarell Quansah",       "Angleterre", "DEF", 7.5),
        p("Nico O'Reilly",        "Angleterre", "DEF", 7.0),
        p("Dan Burn",             "Angleterre", "DEF", 6.5),
        p("Djed Spence",          "Angleterre", "DEF", 7.0),
        p("Declan Rice",          "Angleterre", "MID", 11.5),
        p("Elliot Anderson",      "Angleterre", "MID", 7.5),
        p("Jude Bellingham",      "Angleterre", "MID", 12.0),
        p("Jordan Henderson",     "Angleterre", "MID", 7.5),
        p("Morgan Rogers",        "Angleterre", "MID", 8.0),
        p("Kobbie Mainoo",        "Angleterre", "MID", 9.0),
        p("Eberechi Eze",         "Angleterre", "MID", 9.5),
        p("Harry Kane",           "Angleterre", "FWD", 12.0),
        p("Ivan Toney",           "Angleterre", "FWD", 8.5),
        p("Ollie Watkins",        "Angleterre", "FWD", 9.5),
        p("Bukayo Saka",          "Angleterre", "FWD", 12.0),
        p("Noni Madueke",         "Angleterre", "FWD", 8.5),
        p("Marcus Rashford",      "Angleterre", "FWD", 9.0),
        p("Anthony Gordon",       "Angleterre", "FWD", 8.5),
    ],
    "coaches": [],
},

"Croatie": {
    "groupe": "L",
    "players": [
        p("Dominik Livakovic",   "Croatie", "GK", 8.5),
        p("Dominik Kotarski",    "Croatie", "GK", 6.5),
        p("Ivor Pandur",         "Croatie", "GK", 5.5),
        p("Josko Gvardiol",      "Croatie", "DEF", 11.5),
        p("Duje Caleta-Car",     "Croatie", "DEF", 7.5),
        p("Josip Sutalo",        "Croatie", "DEF", 8.0),
        p("Josip Stanisic",      "Croatie", "DEF", 8.0),
        p("Marin Pongracic",     "Croatie", "DEF", 7.5),
        p("Martin Erlic",        "Croatie", "DEF", 7.0),
        p("Luka Vuskovic",       "Croatie", "DEF", 7.0),
        p("Luka Modric",         "Croatie", "MID", 11.0),
        p("Mateo Kovacic",       "Croatie", "MID", 10.5),
        p("Mario Pasalic",       "Croatie", "MID", 8.0),
        p("Nikola Vlasic",       "Croatie", "MID", 8.5),
        p("Luka Sucic",          "Croatie", "MID", 8.5),
        p("Martin Baturina",     "Croatie", "MID", 8.5),
        p("Kristijan Jakic",     "Croatie", "MID", 7.5),
        p("Petar Sucic",         "Croatie", "MID", 8.0),
        p("Nikola Moro",         "Croatie", "MID", 7.5),
        p("Toni Fruk",           "Croatie", "MID", 6.5),
        p("Ivan Perisic",        "Croatie", "FWD", 9.0),
        p("Andrej Kramaric",     "Croatie", "FWD", 9.5),
        p("Ante Budimir",        "Croatie", "FWD", 7.5),
        p("Marco Pasalic",       "Croatie", "FWD", 6.0),
        p("Petar Musa",          "Croatie", "FWD", 7.5),
        p("Igor Matanovic",      "Croatie", "FWD", 7.0),
    ],
    "coaches": [],
},

"Ghana": {
    "groupe": "L",
    "players": [
        p("Benjamin Asare",       "Ghana", "GK", 5.0),
        p("Lawrence Ati-Zigi",    "Ghana", "GK", 7.0),
        p("Joseph Anang",         "Ghana", "GK", 5.5),
        p("Baba Abdul Rahman",    "Ghana", "DEF", 7.0),
        p("Derrick Luckassen",    "Ghana", "DEF", 6.0),
        p("Gideon Mensah",        "Ghana", "DEF", 7.0),
        p("Marvin Senaya",        "Ghana", "DEF", 6.5),
        p("Alidu Seidu",          "Ghana", "DEF", 7.5),
        p("Abdul Mumin",          "Ghana", "DEF", 7.0),
        p("Jerome Opoku",         "Ghana", "DEF", 6.5),
        p("Jonas Adjetey",        "Ghana", "DEF", 6.5),
        p("Kojo Oppong Peprah",   "Ghana", "DEF", 7.0),
        p("Thomas Partey",        "Ghana", "MID", 10.0),
        p("Kamaldeen Sulemana",   "Ghana", "MID", 9.0),
        p("Kwasi Sibo",           "Ghana", "MID", 6.5),
        p("Augustine Boakye",     "Ghana", "MID", 6.5),
        p("Caleb Yirenkyi",       "Ghana", "MID", 6.5),
        p("Abdul Fatawu Issahaku","Ghana", "MID", 8.5),
        p("Elisha Owusu",         "Ghana", "MID", 7.0),
        p("Christopher Bonsu Baah","Ghana","FWD", 7.5),
        p("Ernest Nuamah",        "Ghana", "FWD", 8.0),
        p("Antoine Semenyo",      "Ghana", "FWD", 9.0),
        p("Brandon Thomas-Asante","Ghana", "FWD", 7.0),
        p("Prince Kwabena Adu",   "Ghana", "FWD", 6.0),
        p("Iñaki Williams",       "Ghana", "FWD", 9.5),
        p("Jordan Ayew",          "Ghana", "FWD", 8.0),
    ],
    "coaches": [],
},

"Panama": {
    "groupe": "L",
    "players": [
        p("Orlando Mosquera",      "Panama", "GK", 6.5),
        p("Luis Mejía",            "Panama", "GK", 6.0),
        p("César Samudio",         "Panama", "GK", 5.5),
        p("César Blackman",        "Panama", "DEF", 6.5),
        p("Jorge Gutiérrez",       "Panama", "DEF", 6.0),
        p("Amir Murillo",          "Panama", "DEF", 7.5),
        p("Fidel Escobar",         "Panama", "DEF", 7.0),
        p("Andrés Andrade",        "Panama", "DEF", 7.0),
        p("Edgardo Fariña",        "Panama", "DEF", 6.0),
        p("José Córdoba",          "Panama", "DEF", 6.5),
        p("Eric Davis",            "Panama", "DEF", 6.0),
        p("Jiovani Ramos",         "Panama", "DEF", 5.5),
        p("Roderick Miller",       "Panama", "DEF", 5.5),
        p("Aníbal Godoy",          "Panama", "MID", 7.5),
        p("Adalberto Carrasquilla","Panama", "MID", 8.0),
        p("Carlos Harvey",         "Panama", "MID", 7.0),
        p("Cristian Martínez",     "Panama", "MID", 6.5),
        p("José Luis Rodríguez",   "Panama", "MID", 6.5),
        p("Cesar Yanis",           "Panama", "MID", 6.5),
        p("Yoel Bárcenas",         "Panama", "MID", 7.5),
        p("Alberto Quintero",      "Panama", "MID", 7.0),
        p("Azarías Londoño",       "Panama", "MID", 6.0),
        p("Ismael Díaz",           "Panama", "FWD", 8.5),
        p("Cecilio Waterman",      "Panama", "FWD", 7.5),
        p("José Fajardo",          "Panama", "FWD", 7.0),
        p("Tomás Rodríguez",       "Panama", "FWD", 7.0),
    ],
    "coaches": [],
},

}  # fin EFFECTIFS


# ══════════════════════════════════════════════════════════════════════════════
#  FONCTIONS D'IMPORT
# ══════════════════════════════════════════════════════════════════════════════

def check_token():
    if ADMIN_TOKEN == "REMPLACE_PAR_TON_TOKEN":
        print("\n❌ ERREUR : Tu n'as pas renseigné ton ADMIN_TOKEN !")
        print("   → Ouvre import_effectifs.py et remplace ADMIN_TOKEN par ton token JWT.")
        print("   → Récupère-le dans ton navigateur : F12 → Application → LocalStorage → fb_token")
        sys.exit(1)


def import_team(nation: str, data: dict) -> dict:
    """Importe les joueurs (+ coaches) d'une nation via l'API."""
    players = data["players"]
    coaches = data.get("coaches", [])
    groupe  = data.get("groupe", "?")

    payload = {"players": players, "coaches": coaches}

    try:
        r = requests.post(
            f"{API_BASE}/api/v1/admin/confirm-import",
            headers=HEADERS,
            json=payload,
            timeout=30,
        )
        if r.status_code == 201:
            d = r.json()
            return {
                "ok": True,
                "inserted_players": d.get("inserted_players", 0),
                "inserted_coaches": d.get("inserted_coaches", 0),
                "skipped":          d.get("skipped_players", 0) + d.get("skipped_coaches", 0),
                "errors":           d.get("errors", []),
            }
        else:
            return {"ok": False, "error": r.text}
    except Exception as e:
        return {"ok": False, "error": str(e)}


def run(filter_groupe: str = None, filter_nation: str = None):
    check_token()

    teams = {k: v for k, v in EFFECTIFS.items()
             if (filter_groupe is None or v["groupe"] == filter_groupe)
             and (filter_nation is None or k == filter_nation)}

    if not teams:
        print(f"❌ Aucune équipe trouvée pour le filtre donné.")
        sys.exit(1)

    total_players  = 0
    total_coaches  = 0
    total_skipped  = 0
    errors_log     = []

    print(f"\n🚀 Import de {len(teams)} équipe(s)...\n")
    print(f"{'Nation':<25} {'Groupe':<8} {'Joueurs':>8} {'Coaches':>8} {'Doublons':>10} {'Statut'}")
    print("─" * 75)

    for nation, data in teams.items():
        result = import_team(nation, data)
        groupe = data.get("groupe", "?")

        if result["ok"]:
            ins_p = result["inserted_players"]
            ins_c = result["inserted_coaches"]
            skip  = result["skipped"]
            errs  = result["errors"]
            total_players += ins_p
            total_coaches += ins_c
            total_skipped += skip

            status = "✅"
            if errs:
                status = f"⚠️  {len(errs)} err"
                errors_log.extend([f"{nation}: {e}" for e in errs])
            elif ins_p + ins_c == 0:
                status = "⏭️  déjà importé"

            print(f"{nation:<25} {groupe:<8} {ins_p:>8} {ins_c:>8} {skip:>10}   {status}")
        else:
            print(f"{nation:<25} {groupe:<8} {'—':>8} {'—':>8} {'—':>10}   ❌ {result['error'][:50]}")
            errors_log.append(f"{nation}: {result['error']}")

        time.sleep(0.1)  # petit délai pour ne pas saturer l'API

    print("─" * 75)
    print(f"\n📊 RÉSUMÉ")
    print(f"   ✅ {total_players} joueurs insérés")
    print(f"   🧑‍💼 {total_coaches} entraîneurs insérés")
    print(f"   ⏭️  {total_skipped} doublons ignorés")

    if errors_log:
        print(f"\n⚠️  {len(errors_log)} erreur(s) :")
        for e in errors_log[:10]:
            print(f"   • {e}")
        if len(errors_log) > 10:
            print(f"   ... et {len(errors_log) - 10} autres")

    print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Import effectifs CdM 2026")
    parser.add_argument("--groupe", help="Filtrer par groupe (ex: C, J, L)")
    parser.add_argument("--nation", help="Filtrer par nation (ex: France)")
    args = parser.parse_args()

    run(filter_groupe=args.groupe, filter_nation=args.nation)